export const FEATURE_FLAGS = {
  UNIFIED_SESSION_MANAGEMENT: process.env.ENABLE_UNIFIED_SESSION_MANAGEMENT === 'true',
  DEPENDENCY_ENFORCEMENT: process.env.ENABLE_DEPENDENCY_ENFORCEMENT === 'true',
  MONITORING_HOOKS: process.env.ENABLE_MONITORING_HOOKS === 'true',
};
