import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import AnimatedCard from "@/components/ui/animated-card";
import { 
  Code2, 
  FileCode, 
  Save, 
  Play, 
  Download,
  Folder,
  File,
  ChevronRight,
  ChevronDown,
  Circle,
  CheckCircle,
  Clock
} from "lucide-react";

interface CodeEditorProps {
  projectId: number;
  selectedFile?: string | null;
  onFileSelect?: (file: string) => void;
}

interface FileNode {
  name: string;
  type: 'file' | 'folder';
  path: string;
  children?: FileNode[];
  status?: 'generating' | 'complete' | 'modified';
  content?: string;
}

const mockFileStructure: FileNode[] = [
  {
    name: 'src',
    type: 'folder',
    path: 'src',
    children: [
      {
        name: 'components',
        type: 'folder',
        path: 'src/components',
        children: [
          { name: 'ProductCard.tsx', type: 'file', path: 'src/components/ProductCard.tsx', status: 'complete' },
          { name: 'Navigation.tsx', type: 'file', path: 'src/components/Navigation.tsx', status: 'complete' },
          { name: 'Cart.tsx', type: 'file', path: 'src/components/Cart.tsx', status: 'generating' }
        ]
      },
      {
        name: 'pages',
        type: 'folder',
        path: 'src/pages',
        children: [
          { name: 'Home.tsx', type: 'file', path: 'src/pages/Home.tsx', status: 'complete' },
          { name: 'Products.tsx', type: 'file', path: 'src/pages/Products.tsx', status: 'generating' }
        ]
      },
      {
        name: 'utils',
        type: 'folder',
        path: 'src/utils',
        children: [
          { name: 'api.ts', type: 'file', path: 'src/utils/api.ts', status: 'complete' },
          { name: 'helpers.ts', type: 'file', path: 'src/utils/helpers.ts', status: 'complete' }
        ]
      },
      { name: 'App.tsx', type: 'file', path: 'src/App.tsx', status: 'complete' },
      { name: 'index.tsx', type: 'file', path: 'src/index.tsx', status: 'complete' }
    ]
  },
  {
    name: 'server',
    type: 'folder',
    path: 'server',
    children: [
      { name: 'index.ts', type: 'file', path: 'server/index.ts', status: 'complete' },
      { name: 'routes.ts', type: 'file', path: 'server/routes.ts', status: 'generating' },
      { name: 'database.ts', type: 'file', path: 'server/database.ts', status: 'complete' }
    ]
  },
  { name: 'package.json', type: 'file', path: 'package.json', status: 'complete' },
  { name: 'tailwind.config.js', type: 'file', path: 'tailwind.config.js', status: 'complete' },
  { name: 'README.md', type: 'file', path: 'README.md', status: 'complete' }
];

const mockFileContent: Record<string, string> = {
  'src/components/ProductCard.tsx': `// Auto-generated by Frontend Agent using React Bits
import { useState } from 'react';
import { AnimatedCard } from '@/components/react-bits';

interface ProductCardProps {
  product: {
    id: string;
    name: string;
    price: number;
    image: string;
    rating: number;
  };
  onAddToCart: (productId: string) => void;
}

export function ProductCard({ product, onAddToCart }: ProductCardProps) {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <AnimatedCard
      className="product-card bg-white rounded-2xl shadow-xl p-6 max-w-sm transform hover:scale-105 transition-all duration-300 border border-slate-200"
      animation="hyperspeed"
      onHover={() => setIsHovered(true)}
      onHoverEnd={() => setIsHovered(false)}
    >
      <div className="w-full h-48 bg-gradient-to-br from-blue-100 to-purple-100 rounded-xl mb-4 flex items-center justify-center overflow-hidden">
        <img 
          src={product.image} 
          alt={product.name}
          className="w-full h-full object-cover"
        />
      </div>
      
      <h3 className="text-xl font-bold text-slate-800 mb-2">{product.name}</h3>
      <p className="text-slate-600 text-sm mb-4">
        High-quality product with excellent features and design.
      </p>
      
      <div className="flex items-center justify-between mb-4">
        <span className="text-2xl font-bold text-slate-800">
          \${product.price.toFixed(2)}
        </span>
        <div className="flex items-center space-x-1">
          <div className="flex text-yellow-400">
            {\`★\`.repeat(product.rating)}
          </div>
          <span className="text-slate-500 text-sm">(248)</span>
        </div>
      </div>
      
      <button 
        onClick={() => onAddToCart(product.id)}
        className="w-full py-3 bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold rounded-xl hover:from-blue-600 hover:to-purple-600 transition-all duration-300 transform hover:scale-105"
      >
        Add to Cart
      </button>
    </AnimatedCard>
  );
}`,
  'src/App.tsx': `import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { Navigation } from './components/Navigation';
import { Home } from './pages/Home';
import { Products } from './pages/Products';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-gray-50">
        <Navigation />
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/products" element={<Products />} />
        </Routes>
      </div>
    </Router>
  );
}

export default App;`,
  'server/index.ts': `import express from 'express';
import cors from 'cors';
import { router as apiRoutes } from './routes';

const app = express();
const PORT = process.env.PORT || 8000;

app.use(cors());
app.use(express.json());
app.use('/api', apiRoutes);

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});`
};

export default function CodeEditor({ projectId, selectedFile, onFileSelect }: CodeEditorProps) {
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['src', 'src/components']));
  const [activeFile, setActiveFile] = useState<string>(selectedFile || 'src/components/ProductCard.tsx');
  const [fileContent, setFileContent] = useState<string>('');
  const [isModified, setIsModified] = useState(false);

  useEffect(() => {
    if (activeFile && mockFileContent[activeFile]) {
      setFileContent(mockFileContent[activeFile]);
      setIsModified(false);
    }
  }, [activeFile]);

  const toggleFolder = (path: string) => {
    setExpandedFolders(prev => {
      const newSet = new Set(prev);
      if (newSet.has(path)) {
        newSet.delete(path);
      } else {
        newSet.add(path);
      }
      return newSet;
    });
  };

  const selectFile = (path: string) => {
    setActiveFile(path);
    onFileSelect?.(path);
  };

  const handleContentChange = (value: string) => {
    setFileContent(value);
    setIsModified(true);
  };

  const saveFile = () => {
    // In a real app, this would save to the backend
    console.log('Saving file:', activeFile, fileContent);
    setIsModified(false);
  };

  const getFileStatusIcon = (status?: string) => {
    switch (status) {
      case 'generating':
        return <Clock className="h-3 w-3 text-blue-400 animate-spin" />;
      case 'complete':
        return <CheckCircle className="h-3 w-3 text-emerald-400" />;
      case 'modified':
        return <Circle className="h-3 w-3 text-orange-400 fill-current" />;
      default:
        return null;
    }
  };

  const renderFileTree = (nodes: FileNode[], depth = 0) => {
    return nodes.map((node) => (
      <div key={node.path} style={{ marginLeft: depth * 16 }}>
        <div
          className={`flex items-center space-x-2 py-1 px-2 rounded cursor-pointer hover:bg-muted/50 transition-colors ${
            activeFile === node.path ? 'bg-primary/20 text-primary' : 'text-muted-foreground hover:text-white'
          }`}
          onClick={() => {
            if (node.type === 'folder') {
              toggleFolder(node.path);
            } else {
              selectFile(node.path);
            }
          }}
        >
          {node.type === 'folder' ? (
            <>
              {expandedFolders.has(node.path) ? (
                <ChevronDown className="h-3 w-3" />
              ) : (
                <ChevronRight className="h-3 w-3" />
              )}
              <Folder className="h-4 w-4" />
            </>
          ) : (
            <>
              <div className="w-3" />
              <File className="h-4 w-4" />
            </>
          )}
          <span className="text-sm flex-1">{node.name}</span>
          {getFileStatusIcon(node.status)}
        </div>
        {node.type === 'folder' && expandedFolders.has(node.path) && node.children && (
          <div>
            {renderFileTree(node.children, depth + 1)}
          </div>
        )}
      </div>
    ));
  };

  const getLanguageFromFile = (filename: string) => {
    if (filename.endsWith('.tsx') || filename.endsWith('.jsx')) return 'javascript';
    if (filename.endsWith('.ts') || filename.endsWith('.js')) return 'javascript';
    if (filename.endsWith('.json')) return 'json';
    if (filename.endsWith('.md')) return 'markdown';
    if (filename.endsWith('.css')) return 'css';
    return 'text';
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 h-[600px]">
      {/* File Explorer */}
      <AnimatedCard className="lg:col-span-1 bg-card border border-border">
        <CardHeader className="pb-3">
          <CardTitle className="text-white text-sm flex items-center">
            <Folder className="mr-2 h-4 w-4" />
            File Explorer
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ScrollArea className="h-[500px]">
            <div className="space-y-1">
              {renderFileTree(mockFileStructure)}
            </div>
          </ScrollArea>
        </CardContent>
      </AnimatedCard>

      {/* Code Editor */}
      <AnimatedCard className="lg:col-span-3 bg-card border border-border">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <FileCode className="h-5 w-5 text-primary" />
              <div>
                <CardTitle className="text-white text-sm">{activeFile}</CardTitle>
                <CardDescription className="text-xs">
                  {getLanguageFromFile(activeFile)} • Auto-generated by Frontend Agent
                </CardDescription>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              {isModified && (
                <Badge variant="secondary" className="bg-orange-500/20 text-orange-400">
                  Modified
                </Badge>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={saveFile}
                disabled={!isModified}
                className="border-primary/30"
              >
                <Save className="mr-2 h-3 w-3" />
                Save
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="border-emerald-500/30 text-emerald-400"
              >
                <Play className="mr-2 h-3 w-3" />
                Run
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div className="relative">
            <textarea
              value={fileContent}
              onChange={(e) => handleContentChange(e.target.value)}
              className="code-editor w-full h-[500px] bg-slate-900 text-white p-4 font-mono text-sm border-none resize-none focus:outline-none"
              spellCheck={false}
            />
            <div className="absolute bottom-4 right-4 flex items-center space-x-2 text-xs text-slate-400">
              <span>Line 1, Col 1</span>
              <span>•</span>
              <span>UTF-8</span>
              <span>•</span>
              <span className="capitalize">{getLanguageFromFile(activeFile)}</span>
            </div>
          </div>
        </CardContent>
      </AnimatedCard>
    </div>
  );
}
