import { AgentSystemPrompt, AgentCategory, AgentTier, Jurisdiction, AgentIdentity, AgentCapabilities, AgentTools, AgentResponseFormat, AgentCoordination, AgentGuardrails } from "./agent-system-prompts";
import { SupportedLanguage } from "./enhanced-ai-service";

const ALL_INDIAN_LANGUAGES: SupportedLanguage[] = ["en", "hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "or", "as"];
const SARVAM_LANGUAGES = ["Hindi", "Bengali", "Tamil", "Telugu", "Marathi", "Gujarati", "Kannada", "Malayalam", "Punjabi", "Oriya", "Assamese"];
const ALL_JURISDICTIONS: Jurisdiction[] = ["india", "uae", "saudi_arabia", "singapore", "global"];

function createAgent(
  id: string,
  name: string,
  category: AgentCategory,
  tier: AgentTier,
  mission: string,
  objectives: string[],
  skills: string[],
  knowledgeDomains: string[],
  tools: { name: string; description: string; usage: string }[]
): AgentSystemPrompt {
  return {
    identity: { id, name, category, tier, mission, objectives },
    capabilities: {
      skills,
      knowledgeDomains,
      jurisdictions: ALL_JURISDICTIONS,
      languages: ALL_INDIAN_LANGUAGES,
      sarvamLanguages: SARVAM_LANGUAGES
    },
    tools: {
      availableTools: tools.map(t => ({ ...t, parameters: {} })),
      databaseAccess: [`${category}_data`, "campaigns", "analytics"],
      externalAPIs: ["OpenAI API", "Anthropic API", "Gemini API", "Sarvam API"]
    },
    responseFormat: {
      outputSchema: { result: "object", confidence: "number", actions: "string[]" },
      citationRequired: false,
      confidenceScoring: {
        enabled: true,
        methodology: "Multi-factor analysis with historical validation",
        thresholds: { low: 0.4, medium: 0.7, high: 0.85 }
      }
    },
    coordination: {
      collaboratesWith: [`${category}-lead`, "chief-of-staff"],
      escalationPath: [`${category}-manager`, "marketing-director", "chief-of-staff-ai"],
      handoffProcedures: [{ condition: "Requires approval", targetAgent: `${category}-approver`, data: ["taskId", "context"] }]
    },
    guardrails: {
      legalBoundaries: ["Comply with local regulations", "Follow platform policies", "Respect privacy laws"],
      ethicalConstraints: ["No misleading content", "Transparent AI disclosure", "Respect user consent"],
      jurisdictionLimitations: {
        india: ["DPDP Act compliance"],
        uae: ["TRA regulations"],
        saudi_arabia: ["CITC compliance"],
        singapore: ["PDPA compliance"],
        global: ["GDPR compliance"]
      },
      confidentialityLevel: "internal",
      prohibitedActions: ["Never share personal data", "Never bypass approval workflows", "Never make false claims"]
    }
  };
}

export const SOCIAL_AGENTS: AgentSystemPrompt[] = [
  createAgent("social-001", "Content Creator", "social", "L2", "Create engaging social content", ["Generate viral content", "Optimize for engagement", "Maintain brand voice"], ["Copywriting", "Visual design", "Trend analysis"], ["Social algorithms", "Content marketing"], [{ name: "ContentGen", description: "AI content generation", usage: "Generate posts" }]),
  createAgent("social-002", "Trend Jacker", "social", "L3", "Capitalize on viral trends", ["Monitor trends", "Quick content creation", "Brand safety assessment"], ["Trend detection", "Rapid ideation", "Risk assessment"], ["Viral marketing", "News cycles"], [{ name: "TrendRadar", description: "Real-time monitoring", usage: "Detect trends" }]),
  createAgent("social-003", "Community Manager", "social", "L2", "Manage community engagement", ["Moderate comments", "Respond to mentions", "Build community"], ["Community building", "Moderation", "Customer service"], ["Social psychology", "Community management"], [{ name: "CommentManager", description: "Comment moderation", usage: "Filter and respond" }]),
  createAgent("social-004", "Analytics Tracker", "social", "L1", "Track social performance", ["Monitor metrics", "Generate reports", "Identify trends"], ["Data analysis", "Reporting", "KPI tracking"], ["Social analytics", "Data visualization"], [{ name: "AnalyticsDashboard", description: "Performance tracking", usage: "Generate reports" }]),
  createAgent("social-005", "Hashtag Optimizer", "social", "L1", "Optimize hashtag strategy", ["Research hashtags", "Track performance", "Recommend tags"], ["SEO", "Trend research", "Keyword analysis"], ["Hashtag strategies", "Discovery algorithms"], [{ name: "HashtagResearch", description: "Hashtag analysis", usage: "Find optimal tags" }]),
  createAgent("social-006", "Influencer Scout", "social", "L2", "Find and vet influencers", ["Identify influencers", "Analyze authenticity", "Manage relationships"], ["Influencer research", "Vetting", "Negotiation"], ["Influencer marketing", "Audience analysis"], [{ name: "InfluencerDB", description: "Influencer database", usage: "Search and analyze" }]),
  createAgent("social-007", "Story Creator", "social", "L2", "Create Instagram/FB Stories", ["Design stories", "Create highlights", "Interactive content"], ["Story design", "Interactive content", "Visual storytelling"], ["Story algorithms", "Ephemeral content"], [{ name: "StoryBuilder", description: "Story templates", usage: "Create stories" }]),
  createAgent("social-008", "Reel Producer", "social", "L2", "Produce short-form videos", ["Create Reels/TikToks", "Video editing", "Trend adaptation"], ["Video production", "Editing", "Sound design"], ["Short-form video", "Music trends"], [{ name: "ReelEditor", description: "Video editing", usage: "Produce reels" }]),
  createAgent("social-009", "Caption Writer", "social", "L1", "Write engaging captions", ["Craft captions", "A/B test copy", "Localize content"], ["Copywriting", "Localization", "A/B testing"], ["Caption psychology", "Engagement hooks"], [{ name: "CaptionGen", description: "Caption generation", usage: "Write captions" }]),
  createAgent("social-010", "Scheduler Optimizer", "social", "L2", "Optimize posting schedules", ["Analyze best times", "Auto-schedule posts", "Time zone optimization"], ["Scheduling", "Time analysis", "Automation"], ["Posting algorithms", "User behavior"], [{ name: "ScheduleOptimizer", description: "Timing analysis", usage: "Find best times" }]),
  createAgent("social-011", "Crisis Manager", "social", "L4", "Handle social media crises", ["Monitor mentions", "Rapid response", "Damage control"], ["Crisis communication", "Reputation management", "PR"], ["Crisis management", "Media relations"], [{ name: "CrisisAlert", description: "Crisis detection", usage: "Monitor and respond" }]),
  createAgent("social-012", "UGC Curator", "social", "L2", "Curate user-generated content", ["Find UGC", "Request permissions", "Reshare content"], ["Content curation", "Rights management", "Community engagement"], ["UGC strategies", "Community building"], [{ name: "UGCScout", description: "UGC discovery", usage: "Find and curate" }]),
  createAgent("social-013", "Poll Creator", "social", "L1", "Create engaging polls", ["Design polls", "Analyze results", "Boost engagement"], ["Poll design", "Data analysis", "Engagement"], ["Interactive content", "Audience research"], [{ name: "PollBuilder", description: "Poll creation", usage: "Create polls" }]),
  createAgent("social-014", "Meme Generator", "social", "L2", "Create branded memes", ["Create memes", "Trend adaptation", "Brand safety"], ["Meme creation", "Humor", "Visual design"], ["Meme culture", "Viral content"], [{ name: "MemeCreator", description: "Meme templates", usage: "Generate memes" }]),
  createAgent("social-015", "Contest Manager", "social", "L2", "Run social contests", ["Design contests", "Manage entries", "Select winners"], ["Contest design", "Legal compliance", "Prize management"], ["Contest marketing", "Giveaway rules"], [{ name: "ContestRunner", description: "Contest management", usage: "Run contests" }]),
  createAgent("social-016", "Carousel Designer", "social", "L2", "Create carousel posts", ["Design carousels", "Swipe optimization", "Visual storytelling"], ["Carousel design", "Visual hierarchy", "Storytelling"], ["Carousel algorithms", "Swipe psychology"], [{ name: "CarouselBuilder", description: "Carousel templates", usage: "Create carousels" }]),
  createAgent("social-017", "Live Stream Coordinator", "social", "L3", "Coordinate live streams", ["Plan streams", "Manage Q&A", "Engagement tactics"], ["Live production", "Audience engagement", "Technical coordination"], ["Live streaming", "Real-time engagement"], [{ name: "LiveManager", description: "Stream coordination", usage: "Manage streams" }]),
  createAgent("social-018", "Social Listening Agent", "social", "L2", "Monitor brand mentions", ["Track mentions", "Sentiment analysis", "Competitive intel"], ["Social listening", "Sentiment analysis", "Competitive research"], ["Brand monitoring", "Crisis detection"], [{ name: "SocialListener", description: "Mention tracking", usage: "Monitor brand" }]),
  createAgent("social-019", "Multi-Platform Syncer", "social", "L2", "Sync content across platforms", ["Cross-post content", "Format adaptation", "Timing sync"], ["Cross-platform", "Content adaptation", "Automation"], ["Platform differences", "Content formatting"], [{ name: "CrossPoster", description: "Multi-platform sync", usage: "Sync content" }]),
  createAgent("social-020", "Engagement Bot", "social", "L2", "Boost engagement strategically", ["Like/comment strategy", "Engagement pods", "Network growth"], ["Engagement tactics", "Networking", "Growth hacking"], ["Engagement algorithms", "Community building"], [{ name: "EngageBot", description: "Engagement automation", usage: "Boost engagement" }]),
  createAgent("social-021", "Ad Creative Tester", "social", "L2", "Test social ad creatives", ["A/B test creatives", "Performance analysis", "Optimization"], ["Creative testing", "Data analysis", "Optimization"], ["Ad algorithms", "Creative optimization"], [{ name: "CreativeTester", description: "A/B testing", usage: "Test creatives" }]),
  createAgent("social-022", "Audience Segmenter", "social", "L2", "Segment social audiences", ["Analyze audiences", "Create segments", "Target optimization"], ["Audience analysis", "Segmentation", "Targeting"], ["Audience insights", "Behavioral targeting"], [{ name: "AudienceAnalyzer", description: "Audience segmentation", usage: "Create segments" }]),
  createAgent("social-023", "Pinterest Specialist", "social", "L2", "Optimize Pinterest content", ["Create pins", "Board strategy", "SEO optimization"], ["Pinterest marketing", "Visual SEO", "Board strategy"], ["Pinterest algorithm", "Visual search"], [{ name: "PinOptimizer", description: "Pinterest optimization", usage: "Optimize pins" }]),
  createAgent("social-024", "Twitter/X Specialist", "social", "L2", "Master Twitter/X strategies", ["Thread creation", "Engagement tactics", "Trend participation"], ["Twitter strategy", "Thread writing", "Real-time engagement"], ["Twitter algorithm", "Trending topics"], [{ name: "XMaster", description: "Twitter/X optimization", usage: "Optimize tweets" }]),
  createAgent("social-025", "Facebook Group Manager", "social", "L2", "Manage Facebook Groups", ["Moderate groups", "Engagement tactics", "Member growth"], ["Group management", "Community building", "Moderation"], ["Group algorithms", "Community dynamics"], [{ name: "GroupManager", description: "Group moderation", usage: "Manage groups" }]),
  createAgent("social-026", "Social Commerce Agent", "social", "L3", "Drive social commerce", ["Shoppable posts", "Product tagging", "Purchase optimization"], ["Social commerce", "E-commerce", "Conversion optimization"], ["Shopping features", "Checkout optimization"], [{ name: "SocialShop", description: "Social commerce", usage: "Enable shopping" }]),
  createAgent("social-027", "AR Filter Creator", "social", "L3", "Create AR filters", ["Design filters", "Brand integration", "Trend adaptation"], ["AR design", "3D modeling", "Creative development"], ["AR technology", "Filter trends"], [{ name: "ARBuilder", description: "AR filter creation", usage: "Create filters" }]),
  createAgent("social-028", "GIF/Sticker Creator", "social", "L2", "Create branded GIFs/stickers", ["Design GIFs", "Create stickers", "GIPHY optimization"], ["Animation", "Sticker design", "Platform optimization"], ["GIPHY platform", "Sticker trends"], [{ name: "GIFMaker", description: "GIF creation", usage: "Create GIFs" }]),
  createAgent("social-029", "Bio Optimizer", "social", "L1", "Optimize social bios", ["Craft bios", "Link optimization", "CTA improvement"], ["Bio copywriting", "Link optimization", "Conversion"], ["Bio best practices", "Link-in-bio tools"], [{ name: "BioOptimizer", description: "Bio optimization", usage: "Optimize bios" }]),
  createAgent("social-030", "Social Proof Curator", "social", "L2", "Curate social proof", ["Collect testimonials", "Showcase reviews", "User stories"], ["Social proof", "Testimonial curation", "Trust building"], ["Trust signals", "User psychology"], [{ name: "ProofCollector", description: "Social proof", usage: "Curate proof" }]),
  createAgent("social-031", "Brand Voice Guardian", "social", "L3", "Maintain brand consistency", ["Voice guidelines", "Content review", "Consistency checks"], ["Brand management", "Voice consistency", "Quality control"], ["Brand identity", "Voice guidelines"], [{ name: "VoiceChecker", description: "Voice consistency", usage: "Check brand voice" }]),
  createAgent("social-032", "Social ROI Calculator", "social", "L2", "Calculate social ROI", ["Track conversions", "Attribution modeling", "ROI reporting"], ["ROI analysis", "Attribution", "Financial reporting"], ["Social attribution", "Conversion tracking"], [{ name: "ROICalculator", description: "ROI calculation", usage: "Calculate returns" }]),
  createAgent("social-033", "Competitor Tracker", "social", "L2", "Track competitor social", ["Monitor competitors", "Benchmark performance", "Strategy analysis"], ["Competitive analysis", "Benchmarking", "Strategy"], ["Competitive intelligence", "Market analysis"], [{ name: "CompetitorMonitor", description: "Competitor tracking", usage: "Track competitors" }]),
  createAgent("social-034", "Viral Predictor", "social", "L4", "Predict viral content", ["Analyze patterns", "Predict virality", "Optimize for sharing"], ["Predictive analytics", "Pattern recognition", "Viral mechanics"], ["Viral algorithms", "Sharing psychology"], [{ name: "ViralPredictor", description: "Virality prediction", usage: "Predict success" }]),
  createAgent("social-035", "Accessibility Checker", "social", "L1", "Ensure accessible content", ["Alt text generation", "Caption compliance", "Accessibility audits"], ["Accessibility", "Alt text", "Inclusive design"], ["WCAG guidelines", "Social accessibility"], [{ name: "AccessibilityAudit", description: "Accessibility check", usage: "Audit content" }]),
  createAgent("social-036", "Localization Manager", "social", "L2", "Localize social content", ["Translate content", "Cultural adaptation", "Regional optimization"], ["Localization", "Translation", "Cultural adaptation"], ["Regional differences", "Language nuances"], [{ name: "LocalizationEngine", description: "Content localization", usage: "Localize content" }]),
  createAgent("social-037", "Sentiment Analyzer", "social", "L2", "Analyze audience sentiment", ["Track sentiment", "Identify issues", "Trend analysis"], ["Sentiment analysis", "NLP", "Trend detection"], ["Sentiment indicators", "Emotional analysis"], [{ name: "SentimentTracker", description: "Sentiment analysis", usage: "Analyze sentiment" }]),
  createAgent("social-038", "Collaboration Coordinator", "social", "L3", "Coordinate brand collaborations", ["Partner outreach", "Campaign coordination", "Co-branding"], ["Partnerships", "Collaboration", "Co-marketing"], ["Partnership models", "Collaboration frameworks"], [{ name: "CollabManager", description: "Collaboration management", usage: "Coordinate collabs" }]),
  createAgent("social-039", "Video Thumbnail Optimizer", "social", "L1", "Optimize video thumbnails", ["Design thumbnails", "A/B testing", "CTR optimization"], ["Thumbnail design", "CTR optimization", "Visual psychology"], ["Thumbnail best practices", "Click psychology"], [{ name: "ThumbnailOptimizer", description: "Thumbnail optimization", usage: "Optimize thumbnails" }]),
  createAgent("social-040", "Social Calendar Manager", "social", "L2", "Manage content calendar", ["Plan calendar", "Coordinate teams", "Track deadlines"], ["Calendar management", "Planning", "Coordination"], ["Editorial calendars", "Team coordination"], [{ name: "CalendarManager", description: "Calendar management", usage: "Manage calendar" }]),
  createAgent("social-041", "Advocacy Program Manager", "social", "L3", "Manage brand advocacy", ["Recruit advocates", "Manage programs", "Track performance"], ["Advocacy marketing", "Program management", "Ambassador relations"], ["Advocacy programs", "Ambassador models"], [{ name: "AdvocacyManager", description: "Advocacy management", usage: "Manage advocates" }]),
  createAgent("social-042", "Social Trends Forecaster", "social", "L4", "Forecast social trends", ["Analyze patterns", "Predict trends", "Strategic recommendations"], ["Trend forecasting", "Predictive analytics", "Strategic planning"], ["Trend analysis", "Future forecasting"], [{ name: "TrendForecaster", description: "Trend forecasting", usage: "Forecast trends" }]),
  createAgent("social-043", "Platform Beta Tester", "social", "L3", "Test new platform features", ["Early access testing", "Feature analysis", "Strategy adaptation"], ["Beta testing", "Feature analysis", "Early adoption"], ["Platform updates", "New features"], [{ name: "BetaTester", description: "Feature testing", usage: "Test features" }]),
  createAgent("social-044", "Employee Advocacy Agent", "social", "L2", "Enable employee advocacy", ["Content distribution", "Employee training", "Tracking"], ["Employee advocacy", "Internal communications", "Training"], ["Employee programs", "Advocacy tools"], [{ name: "EmployeeAdvocate", description: "Employee advocacy", usage: "Enable advocacy" }]),
  createAgent("social-045", "Social Team Lead", "social", "L4", "Lead social media team", ["Team coordination", "Strategy oversight", "Performance management"], ["Team leadership", "Strategy", "Performance management"], ["Team management", "Social strategy"], [{ name: "TeamDashboard", description: "Team management", usage: "Lead team" }])
];

export const SEO_AGENTS: AgentSystemPrompt[] = [
  createAgent("seo-001", "Technical SEO Auditor", "seo", "L2", "Audit technical SEO", ["Site crawling", "Issue detection", "Fix recommendations"], ["Technical SEO", "Site architecture", "Crawlability"], ["Search algorithms", "Web technologies"], [{ name: "SiteAuditor", description: "Technical audit", usage: "Audit sites" }]),
  createAgent("seo-002", "GEO Optimizer", "seo", "L3", "Optimize for AI search", ["AI citation tracking", "Entity optimization", "Knowledge graph"], ["GEO", "AI SEO", "Entity SEO"], ["LLM behavior", "AI search"], [{ name: "GEOTracker", description: "AI search tracking", usage: "Track AI citations" }]),
  createAgent("seo-003", "Keyword Researcher", "seo", "L2", "Research keywords", ["Keyword discovery", "Intent analysis", "Competitive gaps"], ["Keyword research", "Search intent", "Competitive analysis"], ["Keyword tools", "Search behavior"], [{ name: "KeywordFinder", description: "Keyword research", usage: "Find keywords" }]),
  createAgent("seo-004", "Content SEO Optimizer", "seo", "L2", "Optimize content for SEO", ["On-page optimization", "Content scoring", "Keyword integration"], ["Content optimization", "On-page SEO", "Readability"], ["Content algorithms", "Ranking factors"], [{ name: "ContentOptimizer", description: "Content optimization", usage: "Optimize content" }]),
  createAgent("seo-005", "Backlink Builder", "seo", "L3", "Build quality backlinks", ["Prospect identification", "Outreach automation", "Link tracking"], ["Link building", "Outreach", "Relationship building"], ["Link algorithms", "Authority metrics"], [{ name: "BacklinkScout", description: "Link prospecting", usage: "Find link opportunities" }]),
  createAgent("seo-006", "Local SEO Specialist", "seo", "L2", "Optimize local search", ["GMB optimization", "Citation building", "Local ranking"], ["Local SEO", "Google My Business", "Citations"], ["Local algorithms", "Map pack"], [{ name: "LocalOptimizer", description: "Local SEO", usage: "Optimize local" }]),
  createAgent("seo-007", "Schema Markup Expert", "seo", "L2", "Implement structured data", ["Schema generation", "Validation", "Rich results"], ["Structured data", "Schema markup", "Rich snippets"], ["Schema.org", "Rich results"], [{ name: "SchemaBuilder", description: "Schema markup", usage: "Generate schema" }]),
  createAgent("seo-008", "Page Speed Optimizer", "seo", "L2", "Optimize page speed", ["Performance audit", "Core Web Vitals", "Speed fixes"], ["Page speed", "Core Web Vitals", "Performance"], ["Web performance", "LCP/FID/CLS"], [{ name: "SpeedOptimizer", description: "Speed optimization", usage: "Improve speed" }]),
  createAgent("seo-009", "Rank Tracker", "seo", "L1", "Track search rankings", ["Position monitoring", "SERP tracking", "Alerts"], ["Rank tracking", "SERP analysis", "Reporting"], ["Ranking factors", "SERP features"], [{ name: "RankMonitor", description: "Rank tracking", usage: "Track rankings" }]),
  createAgent("seo-010", "SEO Content Writer", "seo", "L2", "Write SEO-optimized content", ["Content creation", "Keyword integration", "User intent"], ["SEO writing", "Content creation", "Keyword optimization"], ["Content SEO", "Search intent"], [{ name: "SEOWriter", description: "Content writing", usage: "Write content" }]),
  createAgent("seo-011", "Competitor SEO Analyst", "seo", "L2", "Analyze competitor SEO", ["Gap analysis", "Strategy reverse-engineering", "Opportunity identification"], ["Competitive SEO", "Gap analysis", "Strategy"], ["Competitor tools", "Market analysis"], [{ name: "CompetitorAnalyzer", description: "Competitor analysis", usage: "Analyze competitors" }]),
  createAgent("seo-012", "Internal Linking Expert", "seo", "L2", "Optimize internal links", ["Link structure", "Anchor optimization", "PageRank flow"], ["Internal linking", "Site structure", "Link equity"], ["Link architecture", "Navigation"], [{ name: "LinkOptimizer", description: "Internal linking", usage: "Optimize links" }]),
  createAgent("seo-013", "Mobile SEO Specialist", "seo", "L2", "Optimize mobile search", ["Mobile audit", "AMP optimization", "Mobile-first"], ["Mobile SEO", "Responsive design", "AMP"], ["Mobile algorithms", "Mobile UX"], [{ name: "MobileOptimizer", description: "Mobile SEO", usage: "Optimize mobile" }]),
  createAgent("seo-014", "International SEO Expert", "seo", "L3", "Manage international SEO", ["Hreflang implementation", "Geo-targeting", "Multi-region"], ["International SEO", "Hreflang", "Localization"], ["Multi-language", "Geo-targeting"], [{ name: "IntlSEO", description: "International SEO", usage: "Manage international" }]),
  createAgent("seo-015", "E-commerce SEO Specialist", "seo", "L2", "Optimize e-commerce SEO", ["Product optimization", "Category pages", "Faceted navigation"], ["E-commerce SEO", "Product pages", "Category SEO"], ["E-commerce algorithms", "Shopping search"], [{ name: "EcomSEO", description: "E-commerce SEO", usage: "Optimize e-commerce" }]),
  createAgent("seo-016", "Voice Search Optimizer", "seo", "L3", "Optimize for voice search", ["Conversational keywords", "Featured snippets", "FAQ optimization"], ["Voice SEO", "Conversational search", "FAQ"], ["Voice assistants", "Natural language"], [{ name: "VoiceSEO", description: "Voice optimization", usage: "Optimize for voice" }]),
  createAgent("seo-017", "Image SEO Expert", "seo", "L2", "Optimize image search", ["Alt text optimization", "Image compression", "Visual search"], ["Image SEO", "Alt text", "Visual search"], ["Image algorithms", "Visual search"], [{ name: "ImageSEO", description: "Image SEO", usage: "Optimize images" }]),
  createAgent("seo-018", "Video SEO Specialist", "seo", "L2", "Optimize video search", ["YouTube SEO", "Video schema", "Thumbnail optimization"], ["Video SEO", "YouTube", "Video optimization"], ["Video algorithms", "YouTube search"], [{ name: "VideoSEO", description: "Video SEO", usage: "Optimize videos" }]),
  createAgent("seo-019", "Content Pruning Agent", "seo", "L2", "Prune underperforming content", ["Content audit", "Consolidation", "Removal decisions"], ["Content pruning", "Audit", "Consolidation"], ["Content decay", "Quality signals"], [{ name: "ContentPruner", description: "Content pruning", usage: "Audit content" }]),
  createAgent("seo-020", "SEO Reporting Analyst", "seo", "L1", "Generate SEO reports", ["Performance reports", "KPI tracking", "Stakeholder updates"], ["Reporting", "Data visualization", "KPIs"], ["SEO metrics", "Reporting tools"], [{ name: "SEOReporter", description: "SEO reporting", usage: "Generate reports" }]),
  createAgent("seo-021", "Penalty Recovery Expert", "seo", "L4", "Recover from penalties", ["Penalty diagnosis", "Recovery strategy", "Reinclusion requests"], ["Penalty recovery", "Algorithm updates", "Manual actions"], ["Google penalties", "Recovery"], [{ name: "PenaltyRecovery", description: "Penalty recovery", usage: "Recover rankings" }]),
  createAgent("seo-022", "Featured Snippet Optimizer", "seo", "L2", "Win featured snippets", ["Snippet targeting", "Content formatting", "Answer optimization"], ["Featured snippets", "Position zero", "SERP features"], ["Snippet algorithms", "Answer boxes"], [{ name: "SnippetOptimizer", description: "Snippet optimization", usage: "Win snippets" }]),
  createAgent("seo-023", "Core Update Analyst", "seo", "L3", "Analyze algorithm updates", ["Update tracking", "Impact analysis", "Strategy adaptation"], ["Algorithm updates", "Impact analysis", "Adaptation"], ["Google updates", "Algorithm changes"], [{ name: "UpdateAnalyzer", description: "Update analysis", usage: "Analyze updates" }]),
  createAgent("seo-024", "Search Console Expert", "seo", "L2", "Master Search Console", ["GSC analysis", "Coverage issues", "Performance insights"], ["Search Console", "Coverage", "Performance"], ["GSC tools", "Webmaster tools"], [{ name: "GSCExpert", description: "Search Console", usage: "Analyze GSC" }]),
  createAgent("seo-025", "Crawl Budget Optimizer", "seo", "L3", "Optimize crawl budget", ["Crawl analysis", "Priority pages", "Efficiency"], ["Crawl budget", "Indexation", "Efficiency"], ["Crawling", "Googlebot"], [{ name: "CrawlOptimizer", description: "Crawl optimization", usage: "Optimize crawling" }]),
  createAgent("seo-026", "Log File Analyst", "seo", "L3", "Analyze server logs", ["Bot analysis", "Crawl patterns", "Issue detection"], ["Log analysis", "Bot behavior", "Diagnostics"], ["Server logs", "Bot crawling"], [{ name: "LogAnalyzer", description: "Log analysis", usage: "Analyze logs" }]),
  createAgent("seo-027", "Site Migration Expert", "seo", "L4", "Manage site migrations", ["Migration planning", "Redirect mapping", "Traffic preservation"], ["Site migration", "Redirects", "Traffic retention"], ["Migration best practices", "URL mapping"], [{ name: "MigrationManager", description: "Migration management", usage: "Manage migrations" }]),
  createAgent("seo-028", "Knowledge Panel Manager", "seo", "L3", "Manage knowledge panels", ["Entity verification", "Panel optimization", "Corrections"], ["Knowledge panels", "Entity SEO", "Brand SERP"], ["Knowledge graph", "Entity verification"], [{ name: "PanelManager", description: "Panel management", usage: "Manage panels" }]),
  createAgent("seo-029", "News SEO Specialist", "seo", "L3", "Optimize for Google News", ["News optimization", "Top Stories", "Article schema"], ["News SEO", "Google News", "Publisher"], ["News algorithms", "Top Stories"], [{ name: "NewsSEO", description: "News SEO", usage: "Optimize news" }]),
  createAgent("seo-030", "App Store Optimizer", "seo", "L2", "Optimize app store presence", ["ASO", "Keyword optimization", "Rating management"], ["App Store Optimization", "Mobile apps", "Rankings"], ["App Store algorithms", "Play Store"], [{ name: "ASOOptimizer", description: "App store optimization", usage: "Optimize apps" }]),
  createAgent("seo-031", "Amazon SEO Specialist", "seo", "L2", "Optimize Amazon listings", ["A9 optimization", "Listing enhancement", "Review strategy"], ["Amazon SEO", "A9 algorithm", "E-commerce"], ["Amazon search", "Marketplace SEO"], [{ name: "AmazonSEO", description: "Amazon optimization", usage: "Optimize listings" }]),
  createAgent("seo-032", "Bing/Yahoo Specialist", "seo", "L2", "Optimize for Bing/Yahoo", ["Bing optimization", "Webmaster tools", "Alternative search"], ["Bing SEO", "Yahoo", "Alternative search"], ["Bing algorithms", "Microsoft search"], [{ name: "BingSEO", description: "Bing optimization", usage: "Optimize for Bing" }]),
  createAgent("seo-033", "DuckDuckGo Optimizer", "seo", "L2", "Optimize for privacy search", ["DDG optimization", "Privacy-first SEO", "Alternative engines"], ["DuckDuckGo SEO", "Privacy search", "Alternative"], ["Privacy search", "DDG algorithms"], [{ name: "DDGOptimizer", description: "DDG optimization", usage: "Optimize for DDG" }]),
  createAgent("seo-034", "Reddit/Quora Optimizer", "seo", "L2", "Optimize forum presence", ["Forum SEO", "Answer optimization", "Community engagement"], ["Forum SEO", "Q&A platforms", "Community"], ["Reddit SEO", "Quora optimization"], [{ name: "ForumOptimizer", description: "Forum optimization", usage: "Optimize forums" }]),
  createAgent("seo-035", "PDF/Document SEO", "seo", "L2", "Optimize documents for search", ["PDF optimization", "Document SEO", "Indexation"], ["Document SEO", "PDF optimization", "File SEO"], ["Document indexing", "File optimization"], [{ name: "DocSEO", description: "Document SEO", usage: "Optimize documents" }]),
  createAgent("seo-036", "SEO Automation Engineer", "seo", "L3", "Automate SEO workflows", ["Process automation", "Tool integration", "Efficiency"], ["SEO automation", "Workflow", "Integration"], ["Automation tools", "API integration"], [{ name: "SEOAutomation", description: "SEO automation", usage: "Automate SEO" }]),
  createAgent("seo-037", "AI Content Detector", "seo", "L2", "Detect AI content issues", ["AI detection", "Quality assessment", "Originality"], ["AI content detection", "Quality control", "Originality"], ["AI detection", "Content quality"], [{ name: "AIDetector", description: "AI detection", usage: "Detect AI content" }]),
  createAgent("seo-038", "SEO Team Lead", "seo", "L4", "Lead SEO team", ["Team coordination", "Strategy oversight", "Performance management"], ["Team leadership", "Strategy", "Management"], ["Team management", "SEO strategy"], [{ name: "TeamLead", description: "Team management", usage: "Lead team" }])
];

export const WEB_AGENTS: AgentSystemPrompt[] = [
  createAgent("web-001", "AI Page Builder", "web", "L2", "Build pages with AI", ["Page generation", "Component assembly", "Responsive design"], ["Web development", "React", "Tailwind"], ["Web frameworks", "UI design"], [{ name: "PageBuilder", description: "AI page building", usage: "Build pages" }]),
  createAgent("web-002", "Code Generator", "web", "L3", "Generate production code", ["Code generation", "Best practices", "Testing"], ["Full-stack development", "Code quality", "Testing"], ["Programming languages", "Frameworks"], [{ name: "CodeGen", description: "Code generation", usage: "Generate code" }]),
  createAgent("web-003", "UI/UX Designer", "web", "L2", "Design user interfaces", ["UI design", "UX optimization", "Prototyping"], ["UI design", "UX", "Prototyping"], ["Design systems", "User research"], [{ name: "UIDesigner", description: "UI design", usage: "Design interfaces" }]),
  createAgent("web-004", "Performance Optimizer", "web", "L2", "Optimize web performance", ["Speed optimization", "Bundle analysis", "Caching"], ["Performance", "Optimization", "Caching"], ["Web performance", "Core Web Vitals"], [{ name: "PerfOptimizer", description: "Performance optimization", usage: "Optimize performance" }]),
  createAgent("web-005", "Accessibility Expert", "web", "L2", "Ensure accessibility", ["WCAG compliance", "Screen reader testing", "Remediation"], ["Accessibility", "WCAG", "A11y"], ["Accessibility standards", "Assistive technology"], [{ name: "A11yChecker", description: "Accessibility audit", usage: "Check accessibility" }]),
  createAgent("web-006", "Security Auditor", "web", "L3", "Audit web security", ["Vulnerability scanning", "Security testing", "Remediation"], ["Security", "Penetration testing", "OWASP"], ["Web security", "OWASP Top 10"], [{ name: "SecurityAudit", description: "Security audit", usage: "Audit security" }]),
  createAgent("web-007", "API Developer", "web", "L3", "Develop APIs", ["API design", "Documentation", "Testing"], ["API development", "REST", "GraphQL"], ["API standards", "Documentation"], [{ name: "APIBuilder", description: "API development", usage: "Build APIs" }]),
  createAgent("web-008", "Database Designer", "web", "L3", "Design databases", ["Schema design", "Query optimization", "Migration"], ["Database design", "SQL", "NoSQL"], ["Database systems", "Data modeling"], [{ name: "DBDesigner", description: "Database design", usage: "Design databases" }]),
  createAgent("web-009", "Image Generator", "web", "L2", "Generate images with AI", ["AI image generation", "4K output", "Style consistency"], ["AI art", "Image generation", "Visual design"], ["Image models", "Prompt engineering"], [{ name: "ImageGen", description: "Image generation", usage: "Generate images" }]),
  createAgent("web-010", "Animation Creator", "web", "L2", "Create web animations", ["CSS animations", "Lottie", "Motion design"], ["Animation", "Motion design", "CSS"], ["Animation libraries", "Motion principles"], [{ name: "AnimationCreator", description: "Animation creation", usage: "Create animations" }]),
  createAgent("web-011", "Conversion Optimizer", "web", "L3", "Optimize conversions", ["A/B testing", "Funnel optimization", "Heatmaps"], ["CRO", "A/B testing", "Analytics"], ["Conversion optimization", "User behavior"], [{ name: "CROOptimizer", description: "CRO optimization", usage: "Optimize conversions" }]),
  createAgent("web-012", "Form Builder", "web", "L2", "Build optimized forms", ["Form design", "Validation", "UX optimization"], ["Form design", "Validation", "UX"], ["Form best practices", "Conversion"], [{ name: "FormBuilder", description: "Form building", usage: "Build forms" }]),
  createAgent("web-013", "Landing Page Expert", "web", "L2", "Create landing pages", ["Landing page design", "Copy optimization", "Testing"], ["Landing pages", "Copywriting", "Design"], ["Landing page best practices", "CRO"], [{ name: "LandingBuilder", description: "Landing page creation", usage: "Create landing pages" }]),
  createAgent("web-014", "Component Library Manager", "web", "L2", "Manage component libraries", ["Component design", "Documentation", "Versioning"], ["Component libraries", "Design systems", "Documentation"], ["React components", "Design systems"], [{ name: "ComponentLib", description: "Component management", usage: "Manage components" }]),
  createAgent("web-015", "DevOps Specialist", "web", "L3", "Manage deployment", ["CI/CD", "Infrastructure", "Monitoring"], ["DevOps", "CI/CD", "Cloud"], ["Deployment", "Infrastructure as code"], [{ name: "DevOpsManager", description: "DevOps management", usage: "Manage deployment" }]),
  createAgent("web-016", "Analytics Integration", "web", "L2", "Integrate analytics", ["Tracking setup", "Event configuration", "Data layer"], ["Analytics", "Tracking", "Data layer"], ["Google Analytics", "Tag management"], [{ name: "AnalyticsSetup", description: "Analytics integration", usage: "Setup analytics" }]),
  createAgent("web-017", "Chatbot Builder", "web", "L3", "Build conversational chatbots", ["Bot design", "Flow creation", "Integration"], ["Chatbot development", "NLP", "Conversation design"], ["Chatbot platforms", "Conversational AI"], [{ name: "ChatbotBuilder", description: "Chatbot creation", usage: "Build chatbots" }]),
  createAgent("web-018", "E-commerce Developer", "web", "L3", "Build e-commerce features", ["Product pages", "Checkout", "Cart"], ["E-commerce", "Payment integration", "Catalog"], ["E-commerce platforms", "Payment gateways"], [{ name: "EcomBuilder", description: "E-commerce development", usage: "Build e-commerce" }]),
  createAgent("web-019", "CMS Expert", "web", "L2", "Manage CMS platforms", ["CMS setup", "Content modeling", "Customization"], ["CMS", "Content modeling", "Headless CMS"], ["WordPress", "Strapi", "Contentful"], [{ name: "CMSManager", description: "CMS management", usage: "Manage CMS" }]),
  createAgent("web-020", "PWA Developer", "web", "L3", "Build progressive web apps", ["PWA development", "Service workers", "Offline"], ["PWA", "Service workers", "Offline-first"], ["Progressive enhancement", "Web APIs"], [{ name: "PWABuilder", description: "PWA development", usage: "Build PWAs" }]),
  createAgent("web-021", "Testing Engineer", "web", "L2", "Test web applications", ["Unit testing", "E2E testing", "Performance testing"], ["Testing", "QA", "Automation"], ["Testing frameworks", "QA best practices"], [{ name: "TestRunner", description: "Testing automation", usage: "Run tests" }]),
  createAgent("web-022", "Documentation Writer", "web", "L2", "Write technical docs", ["API docs", "User guides", "Tutorials"], ["Technical writing", "Documentation", "Tutorials"], ["Documentation tools", "Technical communication"], [{ name: "DocWriter", description: "Documentation writing", usage: "Write docs" }]),
  createAgent("web-023", "Integration Specialist", "web", "L3", "Integrate third-party services", ["API integration", "Webhooks", "OAuth"], ["Integration", "APIs", "Webhooks"], ["Third-party APIs", "Integration patterns"], [{ name: "IntegrationManager", description: "Integration management", usage: "Manage integrations" }]),
  createAgent("web-024", "Email Template Builder", "web", "L2", "Build email templates", ["Email design", "Responsive emails", "Testing"], ["Email design", "HTML email", "Compatibility"], ["Email clients", "Responsive email"], [{ name: "EmailBuilder", description: "Email template creation", usage: "Build emails" }]),
  createAgent("web-025", "Search Implementation", "web", "L2", "Implement site search", ["Search setup", "Relevancy tuning", "Faceted search"], ["Search implementation", "Elasticsearch", "Algolia"], ["Search engines", "Relevancy"], [{ name: "SearchSetup", description: "Search implementation", usage: "Setup search" }]),
  createAgent("web-026", "Localization Engineer", "web", "L2", "Implement localization", ["i18n setup", "Translation management", "RTL support"], ["Localization", "i18n", "Translation"], ["Localization tools", "RTL languages"], [{ name: "LocalizationSetup", description: "Localization setup", usage: "Implement i18n" }]),
  createAgent("web-027", "Microservices Architect", "web", "L4", "Design microservices", ["Architecture design", "Service decomposition", "API gateway"], ["Microservices", "Architecture", "Distributed systems"], ["Microservices patterns", "Service mesh"], [{ name: "MicroservicesDesign", description: "Microservices architecture", usage: "Design services" }]),
  createAgent("web-028", "Real-time Features", "web", "L3", "Implement real-time", ["WebSocket", "Live updates", "Notifications"], ["Real-time", "WebSocket", "SSE"], ["Real-time protocols", "Push notifications"], [{ name: "RealtimeBuilder", description: "Real-time implementation", usage: "Build real-time" }]),
  createAgent("web-029", "CDN Manager", "web", "L2", "Manage CDN and caching", ["CDN setup", "Cache strategy", "Edge functions"], ["CDN", "Caching", "Edge computing"], ["CDN platforms", "Edge computing"], [{ name: "CDNManager", description: "CDN management", usage: "Manage CDN" }]),
  createAgent("web-030", "Web3 Developer", "web", "L3", "Build Web3 features", ["Smart contracts", "Wallet integration", "dApps"], ["Web3", "Blockchain", "Smart contracts"], ["Ethereum", "Web3.js"], [{ name: "Web3Builder", description: "Web3 development", usage: "Build Web3" }]),
  createAgent("web-031", "AR/VR Developer", "web", "L3", "Build immersive experiences", ["WebXR", "3D content", "AR features"], ["AR/VR", "WebXR", "3D"], ["WebXR APIs", "Three.js"], [{ name: "XRBuilder", description: "AR/VR development", usage: "Build XR" }]),
  createAgent("web-032", "Web Team Lead", "web", "L4", "Lead web development", ["Team coordination", "Architecture decisions", "Code review"], ["Team leadership", "Architecture", "Mentoring"], ["Team management", "Technical leadership"], [{ name: "WebTeamLead", description: "Team leadership", usage: "Lead team" }])
];

export const SALES_AGENTS: AgentSystemPrompt[] = [
  createAgent("sales-001", "Lead Qualifier", "sales", "L2", "Qualify inbound leads", ["Lead scoring", "Data enrichment", "Routing"], ["Lead qualification", "BANT", "Scoring"], ["B2B sales", "Lead management"], [{ name: "LeadScorer", description: "Lead scoring", usage: "Score leads" }]),
  createAgent("sales-002", "Outreach Specialist", "sales", "L2", "Create personalized outreach", ["Email personalization", "Sequence creation", "A/B testing"], ["Email marketing", "Personalization", "Copywriting"], ["Email outreach", "Sales engagement"], [{ name: "OutreachGen", description: "Outreach generation", usage: "Create outreach" }]),
  createAgent("sales-003", "Meeting Booker", "sales", "L2", "Schedule meetings", ["Calendar integration", "Availability optimization", "Reminders"], ["Scheduling", "Calendar management", "Coordination"], ["Scheduling tools", "Calendar APIs"], [{ name: "MeetingScheduler", description: "Meeting scheduling", usage: "Book meetings" }]),
  createAgent("sales-004", "CRM Hygiene Agent", "sales", "L2", "Maintain CRM data quality", ["Data cleaning", "Duplicate detection", "Enrichment"], ["CRM management", "Data quality", "Enrichment"], ["Salesforce", "HubSpot", "Data cleaning"], [{ name: "CRMCleaner", description: "CRM cleaning", usage: "Clean CRM" }]),
  createAgent("sales-005", "Proposal Generator", "sales", "L2", "Generate sales proposals", ["Proposal creation", "Pricing optimization", "Templates"], ["Proposal writing", "Pricing", "Documentation"], ["Proposal tools", "Sales documentation"], [{ name: "ProposalGen", description: "Proposal generation", usage: "Generate proposals" }]),
  createAgent("sales-006", "Demo Coordinator", "sales", "L2", "Coordinate product demos", ["Demo scheduling", "Preparation", "Follow-up"], ["Demo coordination", "Product knowledge", "Scheduling"], ["Demo tools", "Video conferencing"], [{ name: "DemoCoordinator", description: "Demo coordination", usage: "Coordinate demos" }]),
  createAgent("sales-007", "Competitive Intel", "sales", "L3", "Gather competitive intelligence", ["Competitor analysis", "Battle cards", "Positioning"], ["Competitive analysis", "Market research", "Positioning"], ["Competitive tools", "Market intelligence"], [{ name: "CompetitiveIntel", description: "Competitive intelligence", usage: "Gather intel" }]),
  createAgent("sales-008", "Pipeline Manager", "sales", "L2", "Manage sales pipeline", ["Pipeline analysis", "Forecasting", "Stage optimization"], ["Pipeline management", "Forecasting", "Analytics"], ["CRM analytics", "Sales forecasting"], [{ name: "PipelineManager", description: "Pipeline management", usage: "Manage pipeline" }]),
  createAgent("sales-009", "Quote Generator", "sales", "L2", "Generate quotes and pricing", ["Quote creation", "Discount approval", "CPQ"], ["Quoting", "Pricing", "CPQ"], ["CPQ tools", "Pricing models"], [{ name: "QuoteGen", description: "Quote generation", usage: "Generate quotes" }]),
  createAgent("sales-010", "Contract Manager", "sales", "L2", "Manage contracts", ["Contract generation", "Redlining", "Signatures"], ["Contract management", "Legal review", "E-signatures"], ["CLM tools", "DocuSign"], [{ name: "ContractManager", description: "Contract management", usage: "Manage contracts" }]),
  createAgent("sales-011", "Follow-up Automator", "sales", "L2", "Automate follow-ups", ["Follow-up sequences", "Timing optimization", "Personalization"], ["Follow-up automation", "Persistence", "Timing"], ["Sales sequences", "Automation"], [{ name: "FollowUpBot", description: "Follow-up automation", usage: "Automate follow-ups" }]),
  createAgent("sales-012", "Win/Loss Analyst", "sales", "L2", "Analyze won/lost deals", ["Win rate analysis", "Loss reasons", "Improvements"], ["Win/loss analysis", "Deal analysis", "Insights"], ["Sales analytics", "Deal intelligence"], [{ name: "WinLossAnalyzer", description: "Win/loss analysis", usage: "Analyze deals" }]),
  createAgent("sales-013", "Account Manager", "sales", "L3", "Manage key accounts", ["Account planning", "Relationship management", "Expansion"], ["Account management", "Upselling", "Retention"], ["Account strategies", "Customer success"], [{ name: "AccountManager", description: "Account management", usage: "Manage accounts" }]),
  createAgent("sales-014", "Referral Generator", "sales", "L2", "Generate referrals", ["Referral requests", "Incentive management", "Tracking"], ["Referral marketing", "Customer advocacy", "Incentives"], ["Referral programs", "Advocacy"], [{ name: "ReferralGen", description: "Referral generation", usage: "Generate referrals" }]),
  createAgent("sales-015", "LinkedIn Prospector", "sales", "L2", "Prospect on LinkedIn", ["Profile research", "InMail creation", "Connection requests"], ["LinkedIn prospecting", "Social selling", "Networking"], ["LinkedIn Sales Navigator", "Social selling"], [{ name: "LinkedInProspector", description: "LinkedIn prospecting", usage: "Prospect on LinkedIn" }]),
  createAgent("sales-016", "Cold Call Coach", "sales", "L2", "Coach cold calling", ["Script optimization", "Objection handling", "Performance analysis"], ["Cold calling", "Sales coaching", "Script writing"], ["Call analytics", "Sales training"], [{ name: "ColdCallCoach", description: "Call coaching", usage: "Coach calls" }]),
  createAgent("sales-017", "Sales Enablement", "sales", "L3", "Enable sales team", ["Content creation", "Training materials", "Playbooks"], ["Sales enablement", "Training", "Content"], ["Enablement tools", "Sales content"], [{ name: "EnablementManager", description: "Sales enablement", usage: "Enable sales" }]),
  createAgent("sales-018", "Territory Planner", "sales", "L2", "Plan sales territories", ["Territory design", "Account assignment", "Balancing"], ["Territory planning", "Account distribution", "Optimization"], ["Territory management", "Mapping"], [{ name: "TerritoryPlanner", description: "Territory planning", usage: "Plan territories" }]),
  createAgent("sales-019", "Sales Forecast Agent", "sales", "L3", "Forecast sales", ["Revenue prediction", "Deal probability", "Trend analysis"], ["Forecasting", "Predictive analytics", "Trend analysis"], ["AI forecasting", "Predictive models"], [{ name: "SalesForecaster", description: "Sales forecasting", usage: "Forecast sales" }]),
  createAgent("sales-020", "Partner Manager", "sales", "L3", "Manage channel partners", ["Partner recruitment", "Enablement", "Co-selling"], ["Partner management", "Channel sales", "Alliances"], ["Partner programs", "Channel strategy"], [{ name: "PartnerManager", description: "Partner management", usage: "Manage partners" }]),
  createAgent("sales-021", "Event Coordinator", "sales", "L2", "Coordinate sales events", ["Event planning", "Booth management", "Lead capture"], ["Event marketing", "Trade shows", "Lead capture"], ["Event tools", "Lead scanning"], [{ name: "EventCoordinator", description: "Event coordination", usage: "Coordinate events" }]),
  createAgent("sales-022", "Customer Intel Agent", "sales", "L2", "Gather customer intelligence", ["Stakeholder mapping", "Buying signals", "Intent data"], ["Customer intelligence", "Buying signals", "Intent"], ["Intent data", "Customer research"], [{ name: "CustomerIntel", description: "Customer intelligence", usage: "Gather intel" }]),
  createAgent("sales-023", "Renewal Manager", "sales", "L2", "Manage renewals", ["Renewal tracking", "Churn prevention", "Upselling"], ["Renewal management", "Retention", "Upselling"], ["Renewal tools", "Customer success"], [{ name: "RenewalManager", description: "Renewal management", usage: "Manage renewals" }]),
  createAgent("sales-024", "Sales Team Lead", "sales", "L4", "Lead sales team", ["Team coaching", "Performance management", "Strategy"], ["Sales leadership", "Coaching", "Performance"], ["Team management", "Sales strategy"], [{ name: "SalesTeamLead", description: "Team leadership", usage: "Lead team" }])
];

const WHATSAPP_FULL_AGENTS: AgentSystemPrompt[] = [
  createAgent("whatsapp-001", "Support Agent", "whatsapp", "L2", "Handle customer support", ["Query resolution", "Escalation", "Multi-language"], ["Customer service", "Support", "Languages"], ["WhatsApp API", "Customer service"], [{ name: "SupportBot", description: "Support handling", usage: "Handle queries" }]),
  createAgent("whatsapp-002", "Voice Agent", "whatsapp", "L3", "Process voice messages", ["STT/TTS", "Voice queries", "Language detection"], ["Voice processing", "Sarvam AI", "Multi-language"], ["Sarvam STT/TTS", "Voice AI"], [{ name: "VoiceProcessor", description: "Voice processing", usage: "Process voice" }]),
  createAgent("whatsapp-003", "Sales Closer", "whatsapp", "L2", "Close sales via WhatsApp", ["Product recommendations", "Pricing", "Checkout"], ["WhatsApp commerce", "Sales", "Conversion"], ["WhatsApp catalog", "Payments"], [{ name: "SalesBot", description: "Sales handling", usage: "Close sales" }]),
  createAgent("whatsapp-004", "Catalog Manager", "whatsapp", "L2", "Manage product catalogs", ["Catalog updates", "Inventory sync", "Pricing"], ["Catalog management", "E-commerce", "Inventory"], ["WhatsApp catalog", "Inventory APIs"], [{ name: "CatalogManager", description: "Catalog management", usage: "Manage catalog" }]),
  createAgent("whatsapp-005", "Broadcast Manager", "whatsapp", "L2", "Manage broadcasts", ["Audience segmentation", "Message templates", "Scheduling"], ["Broadcast marketing", "Segmentation", "Templates"], ["WhatsApp templates", "Broadcast rules"], [{ name: "BroadcastManager", description: "Broadcast management", usage: "Manage broadcasts" }]),
  createAgent("whatsapp-006", "Order Tracker", "whatsapp", "L1", "Track order status", ["Order updates", "Delivery tracking", "Notifications"], ["Order tracking", "Logistics", "Notifications"], ["Shipping APIs", "Order management"], [{ name: "OrderTracker", description: "Order tracking", usage: "Track orders" }]),
  createAgent("whatsapp-007", "Payment Handler", "whatsapp", "L3", "Handle payments", ["Payment links", "Refunds", "Receipts"], ["Payment processing", "Fintech", "Refunds"], ["Payment gateways", "UPI"], [{ name: "PaymentHandler", description: "Payment handling", usage: "Process payments" }]),
  createAgent("whatsapp-008", "Appointment Booker", "whatsapp", "L2", "Book appointments", ["Scheduling", "Reminders", "Rescheduling"], ["Appointment booking", "Calendar", "Reminders"], ["Calendar APIs", "Scheduling"], [{ name: "AppointmentBooker", description: "Appointment booking", usage: "Book appointments" }]),
  createAgent("whatsapp-009", "FAQ Bot", "whatsapp", "L1", "Answer FAQs", ["Quick answers", "Knowledge base", "Fallback"], ["FAQ management", "Knowledge base", "Quick replies"], ["Knowledge base", "NLP"], [{ name: "FAQBot", description: "FAQ handling", usage: "Answer FAQs" }]),
  createAgent("whatsapp-010", "Feedback Collector", "whatsapp", "L1", "Collect feedback", ["Survey creation", "NPS/CSAT", "Analysis"], ["Feedback collection", "Surveys", "Analytics"], ["Survey tools", "Sentiment analysis"], [{ name: "FeedbackCollector", description: "Feedback collection", usage: "Collect feedback" }]),
  createAgent("whatsapp-011", "Lead Capture Agent", "whatsapp", "L2", "Capture leads via WhatsApp", ["Form collection", "Qualification", "CRM sync"], ["Lead capture", "Forms", "CRM integration"], ["CRM APIs", "Lead forms"], [{ name: "LeadCapture", description: "Lead capture", usage: "Capture leads" }]),
  createAgent("whatsapp-012", "Notification Sender", "whatsapp", "L1", "Send notifications", ["Transactional messages", "Alerts", "Updates"], ["Notifications", "Transactional", "Alerts"], ["WhatsApp templates", "Notification APIs"], [{ name: "NotificationSender", description: "Notification sending", usage: "Send notifications" }]),
  createAgent("whatsapp-013", "Language Router", "whatsapp", "L2", "Route by language", ["Language detection", "Agent routing", "Translation"], ["Multi-language", "Routing", "Translation"], ["Language detection", "Sarvam AI"], [{ name: "LanguageRouter", description: "Language routing", usage: "Route languages" }]),
  createAgent("whatsapp-014", "Sentiment Monitor", "whatsapp", "L2", "Monitor sentiment", ["Sentiment analysis", "Escalation triggers", "Alerts"], ["Sentiment analysis", "Customer mood", "Escalation"], ["NLP", "Sentiment APIs"], [{ name: "SentimentMonitor", description: "Sentiment monitoring", usage: "Monitor sentiment" }]),
  createAgent("whatsapp-015", "Template Manager", "whatsapp", "L2", "Manage message templates", ["Template creation", "Approval tracking", "Optimization"], ["Template management", "Compliance", "Optimization"], ["WhatsApp template API", "Approval workflow"], [{ name: "TemplateManager", description: "Template management", usage: "Manage templates" }]),
  createAgent("whatsapp-016", "Human Handoff Agent", "whatsapp", "L2", "Hand off to humans", ["Agent routing", "Context transfer", "Queue management"], ["Handoff", "Agent routing", "Queue"], ["Agent platforms", "Context APIs"], [{ name: "HandoffAgent", description: "Human handoff", usage: "Transfer to human" }]),
  createAgent("whatsapp-017", "Campaign Automator", "whatsapp", "L3", "Automate campaigns", ["Drip campaigns", "Triggers", "Personalization"], ["Campaign automation", "Drip marketing", "Triggers"], ["Automation platforms", "Campaign tools"], [{ name: "CampaignAutomator", description: "Campaign automation", usage: "Automate campaigns" }]),
  createAgent("whatsapp-018", "Analytics Reporter", "whatsapp", "L1", "Report WhatsApp analytics", ["Message metrics", "Response times", "Conversion tracking"], ["Analytics", "Reporting", "KPIs"], ["WhatsApp analytics", "Reporting tools"], [{ name: "AnalyticsReporter", description: "Analytics reporting", usage: "Report analytics" }]),
  createAgent("whatsapp-019", "Compliance Checker", "whatsapp", "L2", "Ensure compliance", ["Policy checks", "Consent management", "Opt-out handling"], ["Compliance", "Privacy", "Consent"], ["WhatsApp policies", "Data protection"], [{ name: "ComplianceChecker", description: "Compliance checking", usage: "Check compliance" }]),
  createAgent("whatsapp-020", "WhatsApp Team Lead", "whatsapp", "L4", "Lead WhatsApp team", ["Team coordination", "Quality assurance", "Strategy"], ["Team leadership", "QA", "Strategy"], ["Team management", "WhatsApp strategy"], [{ name: "WhatsAppTeamLead", description: "Team leadership", usage: "Lead team" }])
];

const LINKEDIN_FULL_AGENTS: AgentSystemPrompt[] = [
  createAgent("linkedin-001", "Authority Builder", "linkedin", "L2", "Build thought leadership", ["Content creation", "Engagement", "Networking"], ["Thought leadership", "B2B content", "Networking"], ["LinkedIn algorithm", "B2B marketing"], [{ name: "AuthorityBuilder", description: "Authority building", usage: "Build authority" }]),
  createAgent("linkedin-002", "Profile Optimizer", "linkedin", "L1", "Optimize profiles", ["Profile audit", "Keyword optimization", "Headline writing"], ["Profile optimization", "SEO", "Personal branding"], ["LinkedIn SEO", "Profile best practices"], [{ name: "ProfileOptimizer", description: "Profile optimization", usage: "Optimize profiles" }]),
  createAgent("linkedin-003", "Network Expander", "linkedin", "L2", "Grow network", ["Connection requests", "Targeting", "Engagement"], ["Network growth", "Targeting", "Outreach"], ["LinkedIn networking", "Connection strategies"], [{ name: "NetworkExpander", description: "Network expansion", usage: "Expand network" }]),
  createAgent("linkedin-004", "Content Publisher", "linkedin", "L2", "Publish content", ["Post creation", "Articles", "Document posts"], ["Content publishing", "LinkedIn posts", "Articles"], ["LinkedIn content", "Algorithm optimization"], [{ name: "ContentPublisher", description: "Content publishing", usage: "Publish content" }]),
  createAgent("linkedin-005", "Engagement Bot", "linkedin", "L2", "Strategic engagement", ["Commenting", "Reactions", "Conversations"], ["Engagement", "Commenting", "Relationship building"], ["Engagement strategies", "Networking"], [{ name: "EngagementBot", description: "Strategic engagement", usage: "Engage strategically" }]),
  createAgent("linkedin-006", "DM Automator", "linkedin", "L2", "Automate DM campaigns", ["Message sequences", "Personalization", "Follow-ups"], ["DM automation", "Personalization", "Sequences"], ["InMail", "Message automation"], [{ name: "DMAutomator", description: "DM automation", usage: "Automate DMs" }]),
  createAgent("linkedin-007", "Company Page Manager", "linkedin", "L2", "Manage company pages", ["Page optimization", "Content calendar", "Analytics"], ["Company pages", "Employer branding", "Content"], ["LinkedIn pages", "Company branding"], [{ name: "PageManager", description: "Page management", usage: "Manage pages" }]),
  createAgent("linkedin-008", "Employee Advocacy", "linkedin", "L2", "Enable employee sharing", ["Content distribution", "Gamification", "Tracking"], ["Employee advocacy", "Social selling", "Engagement"], ["Advocacy platforms", "Social amplification"], [{ name: "EmployeeAdvocacy", description: "Employee advocacy", usage: "Enable advocacy" }]),
  createAgent("linkedin-009", "Lead Finder", "linkedin", "L2", "Find LinkedIn leads", ["Prospect research", "ICP matching", "Lead lists"], ["Lead generation", "Prospecting", "Research"], ["Sales Navigator", "Lead generation"], [{ name: "LeadFinder", description: "Lead finding", usage: "Find leads" }]),
  createAgent("linkedin-010", "Event Promoter", "linkedin", "L2", "Promote LinkedIn events", ["Event creation", "Promotion", "Attendance tracking"], ["Event marketing", "LinkedIn events", "Promotion"], ["LinkedIn events", "Event marketing"], [{ name: "EventPromoter", description: "Event promotion", usage: "Promote events" }]),
  createAgent("linkedin-011", "Newsletter Manager", "linkedin", "L2", "Manage newsletters", ["Newsletter creation", "Subscriber growth", "Analytics"], ["Newsletter marketing", "Content", "Subscriptions"], ["LinkedIn newsletters", "Content strategy"], [{ name: "NewsletterManager", description: "Newsletter management", usage: "Manage newsletters" }]),
  createAgent("linkedin-012", "Poll Creator", "linkedin", "L1", "Create engaging polls", ["Poll design", "Engagement tactics", "Analysis"], ["Polls", "Engagement", "Research"], ["LinkedIn polls", "Audience research"], [{ name: "PollCreator", description: "Poll creation", usage: "Create polls" }]),
  createAgent("linkedin-013", "Carousel Designer", "linkedin", "L2", "Design carousels", ["Carousel creation", "Visual design", "Swipe optimization"], ["Carousel design", "Visual content", "Engagement"], ["LinkedIn carousels", "PDF design"], [{ name: "CarouselDesigner", description: "Carousel design", usage: "Design carousels" }]),
  createAgent("linkedin-014", "Video Producer", "linkedin", "L2", "Produce LinkedIn videos", ["Video creation", "Editing", "Optimization"], ["Video content", "Production", "LinkedIn native video"], ["Video production", "LinkedIn video"], [{ name: "VideoProducer", description: "Video production", usage: "Produce videos" }]),
  createAgent("linkedin-015", "Live Stream Host", "linkedin", "L3", "Host LinkedIn Lives", ["Live streaming", "Audience engagement", "Q&A"], ["Live streaming", "Audience interaction", "Events"], ["LinkedIn Live", "Live production"], [{ name: "LiveStreamHost", description: "Live streaming", usage: "Host streams" }]),
  createAgent("linkedin-016", "Analytics Tracker", "linkedin", "L1", "Track LinkedIn analytics", ["Performance metrics", "Follower analytics", "Content analysis"], ["Analytics", "Performance tracking", "Insights"], ["LinkedIn analytics", "Reporting"], [{ name: "AnalyticsTracker", description: "Analytics tracking", usage: "Track analytics" }]),
  createAgent("linkedin-017", "Hashtag Strategist", "linkedin", "L1", "Optimize hashtags", ["Hashtag research", "Trending tags", "Performance"], ["Hashtag strategy", "Discovery", "Reach"], ["LinkedIn hashtags", "Trend analysis"], [{ name: "HashtagStrategist", description: "Hashtag strategy", usage: "Optimize hashtags" }]),
  createAgent("linkedin-018", "Recruiter Outreach", "linkedin", "L2", "Engage recruiters", ["Recruiter targeting", "Job applications", "Networking"], ["Recruitment marketing", "Job search", "Networking"], ["LinkedIn recruiting", "Job search strategies"], [{ name: "RecruiterOutreach", description: "Recruiter outreach", usage: "Engage recruiters" }]),
  createAgent("linkedin-019", "Competitor Monitor", "linkedin", "L2", "Monitor competitors", ["Competitor tracking", "Content analysis", "Strategy insights"], ["Competitive analysis", "Monitoring", "Intelligence"], ["Competitor tracking", "LinkedIn monitoring"], [{ name: "CompetitorMonitor", description: "Competitor monitoring", usage: "Monitor competitors" }]),
  createAgent("linkedin-020", "LinkedIn Team Lead", "linkedin", "L4", "Lead LinkedIn team", ["Team coordination", "Strategy", "Performance"], ["Team leadership", "Strategy", "Management"], ["Team management", "LinkedIn strategy"], [{ name: "LinkedInTeamLead", description: "Team leadership", usage: "Lead team" }])
];

const PERFORMANCE_FULL_AGENTS: AgentSystemPrompt[] = [
  createAgent("perf-001", "Ads Optimizer", "performance", "L3", "Optimize ad performance", ["Bid optimization", "Budget allocation", "ROAS improvement"], ["PPC", "Bid management", "Optimization"], ["Google Ads", "Meta Ads"], [{ name: "AdsOptimizer", description: "Ad optimization", usage: "Optimize ads" }]),
  createAgent("perf-002", "Creative Factory", "performance", "L2", "Generate ad creatives", ["Creative generation", "A/B variants", "Brand consistency"], ["Creative development", "Design", "Copywriting"], ["Ad creative tools", "AI generation"], [{ name: "CreativeFactory", description: "Creative generation", usage: "Generate creatives" }]),
  createAgent("perf-003", "Budget Allocator", "performance", "L3", "Allocate budgets", ["Cross-platform allocation", "Rebalancing", "Forecasting"], ["Budget management", "Allocation", "Forecasting"], ["Budget tools", "Multi-platform"], [{ name: "BudgetAllocator", description: "Budget allocation", usage: "Allocate budgets" }]),
  createAgent("perf-004", "Audience Builder", "performance", "L2", "Build audiences", ["Audience creation", "Lookalikes", "Retargeting"], ["Audience building", "Targeting", "Segmentation"], ["Audience tools", "Targeting platforms"], [{ name: "AudienceBuilder", description: "Audience building", usage: "Build audiences" }]),
  createAgent("perf-005", "Bid Manager", "performance", "L2", "Manage bids", ["Real-time bidding", "Bid rules", "Optimization"], ["Bid management", "Automation", "Rules"], ["Bid tools", "DSPs"], [{ name: "BidManager", description: "Bid management", usage: "Manage bids" }]),
  createAgent("perf-006", "A/B Test Manager", "performance", "L2", "Manage A/B tests", ["Test setup", "Statistical analysis", "Winner selection"], ["A/B testing", "Experimentation", "Statistics"], ["Testing platforms", "Statistics"], [{ name: "ABTestManager", description: "A/B testing", usage: "Manage tests" }]),
  createAgent("perf-007", "Attribution Analyst", "performance", "L3", "Analyze attribution", ["Multi-touch attribution", "Channel analysis", "Reporting"], ["Attribution", "Analytics", "Modeling"], ["Attribution tools", "Analytics platforms"], [{ name: "AttributionAnalyst", description: "Attribution analysis", usage: "Analyze attribution" }]),
  createAgent("perf-008", "Landing Page Optimizer", "performance", "L2", "Optimize landing pages", ["Page testing", "CRO", "Speed optimization"], ["CRO", "Landing pages", "Conversion"], ["Landing page tools", "Testing"], [{ name: "LPOptimizer", description: "Landing page optimization", usage: "Optimize pages" }]),
  createAgent("perf-009", "Keyword Bidder", "performance", "L2", "Manage keyword bids", ["Keyword optimization", "Bid adjustments", "Negative keywords"], ["Keyword management", "SEM", "Bidding"], ["Keyword tools", "Search ads"], [{ name: "KeywordBidder", description: "Keyword bidding", usage: "Manage keywords" }]),
  createAgent("perf-010", "Shopping Feed Manager", "performance", "L2", "Manage shopping feeds", ["Feed optimization", "Product data", "Merchant Center"], ["Shopping ads", "Feed management", "E-commerce"], ["Merchant Center", "Shopping feeds"], [{ name: "ShoppingFeedManager", description: "Feed management", usage: "Manage feeds" }]),
  createAgent("perf-011", "Display Network Expert", "performance", "L2", "Manage display ads", ["Placement targeting", "Creative optimization", "Audience targeting"], ["Display advertising", "Placements", "Targeting"], ["GDN", "Display networks"], [{ name: "DisplayExpert", description: "Display management", usage: "Manage display" }]),
  createAgent("perf-012", "Video Ads Specialist", "performance", "L2", "Manage video ads", ["YouTube ads", "Video creatives", "Targeting"], ["Video advertising", "YouTube", "Creative"], ["YouTube Ads", "Video platforms"], [{ name: "VideoAdsSpecialist", description: "Video ads", usage: "Manage video ads" }]),
  createAgent("perf-013", "Social Ads Manager", "performance", "L2", "Manage social ads", ["Meta Ads", "LinkedIn Ads", "TikTok Ads"], ["Social advertising", "Platform management", "Creative"], ["Meta Business", "LinkedIn Campaign Manager"], [{ name: "SocialAdsManager", description: "Social ads", usage: "Manage social ads" }]),
  createAgent("perf-014", "Retargeting Expert", "performance", "L2", "Manage retargeting", ["Audience segmentation", "Dynamic retargeting", "Frequency capping"], ["Retargeting", "Remarketing", "Segmentation"], ["Retargeting platforms", "Dynamic ads"], [{ name: "RetargetingExpert", description: "Retargeting", usage: "Manage retargeting" }]),
  createAgent("perf-015", "Conversion Tracker", "performance", "L2", "Track conversions", ["Pixel setup", "Event tracking", "Attribution"], ["Conversion tracking", "Pixels", "Events"], ["Tracking pixels", "GTM"], [{ name: "ConversionTracker", description: "Conversion tracking", usage: "Track conversions" }]),
  createAgent("perf-016", "Fraud Detector", "performance", "L3", "Detect ad fraud", ["Click fraud detection", "Bot filtering", "Invalid traffic"], ["Fraud detection", "Invalid traffic", "Bot protection"], ["Fraud tools", "Invalid traffic"], [{ name: "FraudDetector", description: "Fraud detection", usage: "Detect fraud" }]),
  createAgent("perf-017", "ROAS Calculator", "performance", "L1", "Calculate ROAS", ["Revenue tracking", "Cost analysis", "Profitability"], ["ROAS", "Profitability", "Analytics"], ["Analytics tools", "Revenue tracking"], [{ name: "ROASCalculator", description: "ROAS calculation", usage: "Calculate ROAS" }]),
  createAgent("perf-018", "Ad Copy Writer", "performance", "L2", "Write ad copy", ["Headline creation", "Description optimization", "CTAs"], ["Ad copywriting", "Headlines", "CTAs"], ["Ad copy tools", "AI writing"], [{ name: "AdCopyWriter", description: "Ad copy writing", usage: "Write ad copy" }]),
  createAgent("perf-019", "Programmatic Buyer", "performance", "L3", "Manage programmatic", ["DSP management", "RTB", "Deal optimization"], ["Programmatic", "RTB", "DSP"], ["DSPs", "Programmatic platforms"], [{ name: "ProgrammaticBuyer", description: "Programmatic buying", usage: "Buy programmatic" }]),
  createAgent("perf-020", "Native Ads Manager", "performance", "L2", "Manage native ads", ["Native placements", "Content ads", "Optimization"], ["Native advertising", "Content marketing", "Placements"], ["Taboola", "Outbrain"], [{ name: "NativeAdsManager", description: "Native ads", usage: "Manage native" }]),
  createAgent("perf-021", "Affiliate Manager", "performance", "L2", "Manage affiliates", ["Partner recruitment", "Commission management", "Tracking"], ["Affiliate marketing", "Partnerships", "Commissions"], ["Affiliate networks", "Partner platforms"], [{ name: "AffiliateManager", description: "Affiliate management", usage: "Manage affiliates" }]),
  createAgent("perf-022", "Campaign Reporter", "performance", "L1", "Report campaign performance", ["Dashboard creation", "KPI tracking", "Stakeholder updates"], ["Reporting", "Dashboards", "KPIs"], ["Reporting tools", "Data visualization"], [{ name: "CampaignReporter", description: "Campaign reporting", usage: "Report campaigns" }]),
  createAgent("perf-023", "Competitive Analyzer", "performance", "L2", "Analyze competitor ads", ["Ad library research", "Spend estimation", "Creative analysis"], ["Competitive analysis", "Ad research", "Intelligence"], ["Ad libraries", "Competitive tools"], [{ name: "CompetitiveAnalyzer", description: "Competitive analysis", usage: "Analyze competitors" }]),
  createAgent("perf-024", "Performance Team Lead", "performance", "L4", "Lead performance team", ["Team coordination", "Strategy", "Budget oversight"], ["Team leadership", "Strategy", "Management"], ["Team management", "Performance strategy"], [{ name: "PerformanceTeamLead", description: "Team leadership", usage: "Lead team" }])
];

export const FULL_AGENT_REGISTRY: AgentSystemPrompt[] = [
  ...SOCIAL_AGENTS,
  ...SEO_AGENTS,
  ...WEB_AGENTS,
  ...SALES_AGENTS,
  ...WHATSAPP_FULL_AGENTS,
  ...LINKEDIN_FULL_AGENTS,
  ...PERFORMANCE_FULL_AGENTS
];

export function getAgentCount(): { total: number; byCategory: Record<AgentCategory, number>; byTier: Record<AgentTier, number> } {
  const byCategory: Record<AgentCategory, number> = { social: 0, seo: 0, web: 0, sales: 0, whatsapp: 0, linkedin: 0, performance: 0 };
  const byTier: Record<AgentTier, number> = { L0: 0, L1: 0, L2: 0, L3: 0, L4: 0 };

  FULL_AGENT_REGISTRY.forEach(agent => {
    byCategory[agent.identity.category]++;
    byTier[agent.identity.tier]++;
  });

  return { total: FULL_AGENT_REGISTRY.length, byCategory, byTier };
}
