import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable';
import { ScrollArea } from '@/components/ui/scroll-area';
import { 
  Terminal, 
  FileText, 
  Database, 
  Play, 
  Bug, 
  GitBranch, 
  Package,
  Search,
  Settings,
  BarChart3,
  Zap,
  Code2,
  Folder,
  File,
  ChevronRight,
  ChevronDown,
  Cpu,
  Network,
  Shield,
  Rocket,
  TestTube,
  Monitor,
  Cloud
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import * as monaco from 'monaco-editor';

interface AdvancedIDEProps {
  projectId: string;
  projectName?: string;
  onClose?: () => void;
  onProjectChange?: () => void;
}

interface FileSystemItem {
  name: string;
  type: 'file' | 'folder';
  path: string;
  children?: FileSystemItem[];
  content?: string;
}

interface TerminalSession {
  id: string;
  name: string;
  active: boolean;
  history: Array<{ command: string; output: string; timestamp: Date }>;
}

interface TestResult {
  name: string;
  status: 'passed' | 'failed' | 'running';
  duration?: number;
  error?: string;
}

export default function AdvancedIDEInterface({ projectId, projectName, onClose, onProjectChange }: AdvancedIDEProps) {
  // IDE State Management
  const [activePanel, setActivePanel] = useState<'explorer' | 'search' | 'git' | 'debug'>('explorer');
  const [openFiles, setOpenFiles] = useState<string[]>(['src/App.tsx']);
  const [activeFile, setActiveFile] = useState<string>('src/App.tsx');
  const [terminalSessions, setTerminalSessions] = useState<TerminalSession[]>([
    { id: '1', name: 'Terminal 1', active: true, history: [] }
  ]);
  const [activeTerminal, setActiveTerminal] = useState<string>('1');
  const [terminalInput, setTerminalInput] = useState<string>('');
  const [fileSystem, setFileSystem] = useState<FileSystemItem[]>([
    {
      name: 'src',
      type: 'folder',
      path: 'src',
      children: [
        { name: 'App.tsx', type: 'file', path: 'src/App.tsx', content: '// Your React app starts here\nimport React from "react";\n\nfunction App() {\n  return <div>Hello World</div>;\n}\n\nexport default App;' },
        { name: 'components', type: 'folder', path: 'src/components', children: [] },
        { name: 'hooks', type: 'folder', path: 'src/hooks', children: [] },
        { name: 'utils', type: 'folder', path: 'src/utils', children: [] }
      ]
    },
    { name: 'package.json', type: 'file', path: 'package.json', content: '{\n  "name": "' + projectName.toLowerCase() + '",\n  "version": "1.0.0"\n}' },
    { name: 'README.md', type: 'file', path: 'README.md', content: '# ' + projectName + '\n\nGenerated by WAI DevStudio' }
  ]);

  // Performance Metrics
  const [metrics, setMetrics] = useState({
    cpuUsage: 45,
    memoryUsage: 68,
    networkLatency: 23,
    buildTime: 2.3,
    testCoverage: 87
  });

  // AI Assistant State
  const [aiSuggestions, setAiSuggestions] = useState<string[]>([
    'Add error handling to this component',
    'Optimize this function for better performance', 
    'Add TypeScript types for better safety'
  ]);

  // Testing State
  const [testResults, setTestResults] = useState<TestResult[]>([
    { name: 'App.test.tsx', status: 'passed', duration: 0.8 },
    { name: 'utils.test.tsx', status: 'passed', duration: 0.3 },
    { name: 'api.test.tsx', status: 'failed', duration: 1.2, error: 'Expected 200 but got 404' }
  ]);

  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);
  const terminalRef = useRef<HTMLDivElement>(null);

  // Initialize Monaco Editor
  useEffect(() => {
    if (editorRef.current) return;

    const editor = monaco.editor.create(document.getElementById('monaco-editor')!, {
      value: getFileContent(activeFile),
      language: getFileLanguage(activeFile),
      theme: 'vs-dark',
      fontSize: 14,
      minimap: { enabled: true },
      automaticLayout: true,
      wordWrap: 'on',
      suggestOnTriggerCharacters: true,
      quickSuggestions: true,
      folding: true,
      renderWhitespace: 'boundary'
    });

    editorRef.current = editor;

    // AI-powered code completion
    monaco.languages.registerCompletionItemProvider('typescript', {
      provideCompletionItems: (model, position) => {
        const suggestions = [
          {
            label: 'useState',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'useState(${1:initialValue})',
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            documentation: 'React hook for state management'
          },
          {
            label: 'useEffect',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'useEffect(() => {\n\t${1:// effect logic}\n}, [${2:dependencies}])',
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            documentation: 'React hook for side effects'
          }
        ];
        return { suggestions };
      }
    });

    return () => {
      editor.dispose();
    };
  }, [activeFile]);

  const getFileContent = (filePath: string): string => {
    const findFile = (items: FileSystemItem[], path: string): FileSystemItem | null => {
      for (const item of items) {
        if (item.path === path) return item;
        if (item.children) {
          const found = findFile(item.children, path);
          if (found) return found;
        }
      }
      return null;
    };

    const file = findFile(fileSystem, filePath);
    return file?.content || '// File not found';
  };

  const getFileLanguage = (filePath: string): string => {
    const ext = filePath.split('.').pop();
    switch (ext) {
      case 'tsx': case 'ts': return 'typescript';
      case 'jsx': case 'js': return 'javascript';
      case 'css': return 'css';
      case 'html': return 'html';
      case 'json': return 'json';
      case 'md': return 'markdown';
      default: return 'plaintext';
    }
  };

  const executeTerminalCommand = async (command: string) => {
    const session = terminalSessions.find(s => s.id === activeTerminal);
    if (!session) return;

    // Simulate command execution with AI-powered suggestions
    let output = '';
    
    switch (command.trim()) {
      case 'npm install':
        output = '✅ Installing dependencies...\n📦 Added 847 packages in 23.4s\n🎉 Installation complete!';
        break;
      case 'npm run build':
        output = '🔨 Building project...\n✨ Build completed in 2.3s\n📊 Bundle size: 234kb (gzipped: 67kb)';
        break;
      case 'npm test':
        output = '🧪 Running tests...\n✅ 12 tests passed\n❌ 1 test failed\n📊 Coverage: 87%';
        break;
      case 'git status':
        output = 'On branch main\nYour branch is up to date with \'origin/main\'.\n\nChanges not staged for commit:\n  modified:   src/App.tsx';
        break;
      default:
        output = `Command '${command}' executed\n💡 AI Suggestion: Try 'npm run dev' to start development server`;
    }

    const updatedSession = {
      ...session,
      history: [...session.history, { command, output, timestamp: new Date() }]
    };

    setTerminalSessions(prev => 
      prev.map(s => s.id === activeTerminal ? updatedSession : s)
    );
    setTerminalInput('');
  };

  const FileExplorer = ({ items }: { items: FileSystemItem[] }) => (
    <div className="space-y-1">
      {items.map((item) => (
        <div key={item.path}>
          <div 
            className={`flex items-center gap-2 px-2 py-1 hover:bg-accent rounded cursor-pointer ${
              activeFile === item.path ? 'bg-accent' : ''
            }`}
            onClick={() => {
              if (item.type === 'file') {
                setActiveFile(item.path);
                if (!openFiles.includes(item.path)) {
                  setOpenFiles(prev => [...prev, item.path]);
                }
              }
            }}
          >
            {item.type === 'folder' ? (
              <>
                <ChevronRight className="w-4 h-4" />
                <Folder className="w-4 h-4 text-blue-500" />
              </>
            ) : (
              <>
                <div className="w-4" />
                <File className="w-4 h-4 text-gray-400" />
              </>
            )}
            <span className="text-sm">{item.name}</span>
          </div>
          {item.children && (
            <div className="ml-4">
              <FileExplorer items={item.children} />
            </div>
          )}
        </div>
      ))}
    </div>
  );

  const PerformanceMetrics = () => (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Cpu className="w-4 h-4 text-blue-500" />
        <span className="text-sm">CPU Usage: {metrics.cpuUsage}%</span>
        <div className="flex-1 bg-gray-200 rounded-full h-2">
          <div className="bg-blue-500 h-2 rounded-full" style={{ width: `${metrics.cpuUsage}%` }} />
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Network className="w-4 h-4 text-green-500" />
        <span className="text-sm">Memory: {metrics.memoryUsage}%</span>
        <div className="flex-1 bg-gray-200 rounded-full h-2">
          <div className="bg-green-500 h-2 rounded-full" style={{ width: `${metrics.memoryUsage}%` }} />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-4 text-sm">
        <div>Network: {metrics.networkLatency}ms</div>
        <div>Build: {metrics.buildTime}s</div>
        <div>Coverage: {metrics.testCoverage}%</div>
        <div>Status: ✅ Healthy</div>
      </div>
    </div>
  );

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className="fixed inset-0 bg-background z-50 flex flex-col"
    >
      {/* IDE Header */}
      <div className="flex items-center justify-between p-4 border-b bg-card">
        <div className="flex items-center gap-4">
          <Code2 className="w-6 h-6 text-primary" />
          <h1 className="text-xl font-bold">{projectName} - Advanced IDE</h1>
          <Badge variant="secondary">Phase 3 Features</Badge>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" className="gap-2">
            <Play className="w-4 h-4" />
            Run
          </Button>
          <Button size="sm" variant="outline" className="gap-2">
            <Bug className="w-4 h-4" />
            Debug
          </Button>
          <Button size="sm" variant="outline" className="gap-2">
            <Rocket className="w-4 h-4" />
            Deploy
          </Button>
          <Button variant="ghost" size="sm" onClick={onClose}>
            ✕
          </Button>
        </div>
      </div>

      {/* IDE Main Interface */}
      <div className="flex-1 flex">
        {/* Sidebar */}
        <div className="w-64 border-r bg-card flex flex-col">
          {/* Sidebar Tabs */}
          <div className="flex border-b">
            {[
              { id: 'explorer', icon: Folder, label: 'Explorer' },
              { id: 'search', icon: Search, label: 'Search' },
              { id: 'git', icon: GitBranch, label: 'Git' },
              { id: 'debug', icon: Bug, label: 'Debug' },
            ].map((tab) => (
              <Button
                key={tab.id}
                variant={activePanel === tab.id ? 'secondary' : 'ghost'}
                size="sm"
                className="flex-1 gap-1"
                onClick={() => setActivePanel(tab.id as any)}
              >
                <tab.icon className="w-4 h-4" />
                <span className="text-xs">{tab.label}</span>
              </Button>
            ))}
          </div>

          {/* Sidebar Content */}
          <ScrollArea className="flex-1 p-4">
            {activePanel === 'explorer' && (
              <div>
                <h3 className="font-medium mb-2 flex items-center gap-2">
                  <Folder className="w-4 h-4" />
                  {projectName}
                </h3>
                <FileExplorer items={fileSystem} />
              </div>
            )}

            {activePanel === 'search' && (
              <div className="space-y-4">
                <Input placeholder="Search in files..." />
                <div className="space-y-2">
                  <div className="text-sm text-muted-foreground">Recent searches:</div>
                  <div className="space-y-1 text-sm">
                    <div>useState</div>
                    <div>interface</div>
                    <div>export</div>
                  </div>
                </div>
              </div>
            )}

            {activePanel === 'git' && (
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <GitBranch className="w-4 h-4" />
                  <span className="text-sm font-medium">main</span>
                </div>
                <div className="space-y-2">
                  <div className="text-sm text-muted-foreground">Changes (1)</div>
                  <div className="text-sm bg-yellow-100 dark:bg-yellow-900/20 p-2 rounded">
                    M src/App.tsx
                  </div>
                </div>
                <Button size="sm" className="w-full gap-2">
                  <GitBranch className="w-4 h-4" />
                  Commit Changes
                </Button>
              </div>
            )}

            {activePanel === 'debug' && (
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Bug className="w-4 h-4" />
                  <span className="text-sm font-medium">Debug Console</span>
                </div>
                <div className="space-y-2">
                  <Button size="sm" className="w-full gap-2">
                    <Play className="w-4 h-4" />
                    Start Debugging
                  </Button>
                  <div className="text-xs text-muted-foreground">
                    Breakpoints: 0
                  </div>
                </div>
              </div>
            )}
          </ScrollArea>
        </div>

        {/* Main Editor Area */}
        <ResizablePanelGroup direction="vertical" className="flex-1">
          {/* Code Editor */}
          <ResizablePanel defaultSize={70}>
            <div className="h-full flex flex-col">
              {/* File Tabs */}
              <div className="flex border-b bg-muted/50">
                {openFiles.map((file) => (
                  <div
                    key={file}
                    className={`px-4 py-2 border-r cursor-pointer flex items-center gap-2 ${
                      activeFile === file ? 'bg-background' : 'hover:bg-background/50'
                    }`}
                    onClick={() => setActiveFile(file)}
                  >
                    <File className="w-4 h-4" />
                    <span className="text-sm">{file.split('/').pop()}</span>
                    <button
                      className="ml-2 hover:bg-destructive/20 rounded px-1"
                      onClick={(e) => {
                        e.stopPropagation();
                        setOpenFiles(prev => prev.filter(f => f !== file));
                        if (activeFile === file) {
                          const remaining = openFiles.filter(f => f !== file);
                          setActiveFile(remaining[0] || '');
                        }
                      }}
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>

              {/* Monaco Editor Container */}
              <div className="flex-1 relative">
                <div id="monaco-editor" className="absolute inset-0" />
                
                {/* AI Assistant Overlay */}
                <div className="absolute top-4 right-4 space-y-2">
                  {aiSuggestions.map((suggestion, i) => (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      className="bg-primary/10 border border-primary/20 rounded-lg p-3 max-w-xs"
                    >
                      <div className="flex items-start gap-2">
                        <Zap className="w-4 h-4 text-primary mt-0.5" />
                        <div>
                          <div className="text-sm font-medium">AI Suggestion</div>
                          <div className="text-xs text-muted-foreground">{suggestion}</div>
                          <Button size="sm" className="mt-2 text-xs h-6">
                            Apply
                          </Button>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </div>
            </div>
          </ResizablePanel>

          <ResizableHandle />

          {/* Bottom Panel */}
          <ResizablePanel defaultSize={30}>
            <Tabs defaultValue="terminal" className="h-full">
              <TabsList className="grid w-full grid-cols-5">
                <TabsTrigger value="terminal" className="gap-2">
                  <Terminal className="w-4 h-4" />
                  Terminal
                </TabsTrigger>
                <TabsTrigger value="tests" className="gap-2">
                  <TestTube className="w-4 h-4" />
                  Tests
                </TabsTrigger>
                <TabsTrigger value="performance" className="gap-2">
                  <BarChart3 className="w-4 h-4" />
                  Performance
                </TabsTrigger>
                <TabsTrigger value="database" className="gap-2">
                  <Database className="w-4 h-4" />
                  Database
                </TabsTrigger>
                <TabsTrigger value="deployment" className="gap-2">
                  <Cloud className="w-4 h-4" />
                  Deploy
                </TabsTrigger>
              </TabsList>

              <TabsContent value="terminal" className="h-full p-4">
                <div className="h-full flex flex-col bg-black text-green-400 rounded-lg p-4 font-mono text-sm">
                  <ScrollArea className="flex-1 mb-4" ref={terminalRef}>
                    {terminalSessions.find(s => s.id === activeTerminal)?.history.map((entry, i) => (
                      <div key={i} className="mb-2">
                        <div className="text-blue-400">$ {entry.command}</div>
                        <div className="whitespace-pre-wrap">{entry.output}</div>
                      </div>
                    ))}
                  </ScrollArea>
                  <div className="flex items-center gap-2">
                    <span className="text-blue-400">$</span>
                    <Input
                      value={terminalInput}
                      onChange={(e) => setTerminalInput(e.target.value)}
                      onKeyPress={(e) => {
                        if (e.key === 'Enter') {
                          executeTerminalCommand(terminalInput);
                        }
                      }}
                      className="flex-1 bg-transparent border-none text-green-400 focus:ring-0"
                      placeholder="Enter command..."
                    />
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="tests" className="h-full p-4">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium">Test Results</h3>
                    <Button size="sm" className="gap-2">
                      <Play className="w-4 h-4" />
                      Run All Tests
                    </Button>
                  </div>
                  <ScrollArea className="h-48">
                    {testResults.map((test, i) => (
                      <div key={i} className="flex items-center justify-between p-2 border rounded mb-2">
                        <div className="flex items-center gap-2">
                          <div className={`w-2 h-2 rounded-full ${
                            test.status === 'passed' ? 'bg-green-500' : 
                            test.status === 'failed' ? 'bg-red-500' : 'bg-yellow-500'
                          }`} />
                          <span className="text-sm">{test.name}</span>
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {test.duration}s
                        </div>
                      </div>
                    ))}
                  </ScrollArea>
                </div>
              </TabsContent>

              <TabsContent value="performance" className="h-full p-4">
                <PerformanceMetrics />
              </TabsContent>

              <TabsContent value="database" className="h-full p-4">
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <Database className="w-4 h-4" />
                    <span className="font-medium">Database Connection</span>
                    <Badge variant="secondary">Connected</Badge>
                  </div>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>Tables: 5</div>
                    <div>Records: 1,247</div>
                    <div>Size: 2.3 MB</div>
                    <div>Status: ✅ Healthy</div>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="deployment" className="h-full p-4">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium">Deployment Pipeline</h3>
                    <Button size="sm" className="gap-2">
                      <Rocket className="w-4 h-4" />
                      Deploy Now
                    </Button>
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-green-500 rounded-full" />
                      <span className="text-sm">Build: ✅ Passed</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-green-500 rounded-full" />
                      <span className="text-sm">Tests: ✅ Passed</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-yellow-500 rounded-full" />
                      <span className="text-sm">Security: ⏳ Scanning</span>
                    </div>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </ResizablePanel>
        </ResizablePanelGroup>

        {/* Right Sidebar - AI Assistant & Tools */}
        <div className="w-80 border-l bg-card p-4">
          <Tabs defaultValue="assistant" className="h-full">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="assistant">AI</TabsTrigger>
              <TabsTrigger value="tools">Tools</TabsTrigger>
              <TabsTrigger value="agents">Agents</TabsTrigger>
            </TabsList>

            <TabsContent value="assistant" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Zap className="w-5 h-5" />
                    AI Assistant
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="text-sm text-muted-foreground">
                    Get AI-powered suggestions and code improvements
                  </div>
                  <Button className="w-full gap-2">
                    <Code2 className="w-4 h-4" />
                    Generate Code
                  </Button>
                  <Button variant="outline" className="w-full gap-2">
                    <Shield className="w-4 h-4" />
                    Security Scan
                  </Button>
                  <Button variant="outline" className="w-full gap-2">
                    <BarChart3 className="w-4 h-4" />
                    Performance Audit
                  </Button>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="tools" className="space-y-4">
              <div className="grid grid-cols-2 gap-2">
                <Button size="sm" variant="outline" className="gap-1">
                  <Package className="w-4 h-4" />
                  NPM
                </Button>
                <Button size="sm" variant="outline" className="gap-1">
                  <GitBranch className="w-4 h-4" />
                  Git
                </Button>
                <Button size="sm" variant="outline" className="gap-1">
                  <Database className="w-4 h-4" />
                  DB
                </Button>
                <Button size="sm" variant="outline" className="gap-1">
                  <Monitor className="w-4 h-4" />
                  Monitor
                </Button>
              </div>
            </TabsContent>

            <TabsContent value="agents" className="space-y-2">
              {['Frontend Agent', 'Backend Agent', 'DevOps Agent', 'QA Agent'].map(agent => (
                <div key={agent} className="flex items-center justify-between p-2 border rounded">
                  <span className="text-sm">{agent}</span>
                  <div className="w-2 h-2 bg-green-500 rounded-full" />
                </div>
              ))}
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </motion.div>
  );
}