import { useState, useRef, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cn } from '@/lib/utils';

interface CodeEditorProps {
  projectId: number;
  className?: string;
  height?: string;
}

export function CodeEditor({ projectId, className, height = 'h-96' }: CodeEditorProps) {
  const [selectedFile, setSelectedFile] = useState('src/App.tsx');
  const [activeAgent, setActiveAgent] = useState('Frontend Agent');
  const [isEditing, setIsEditing] = useState(false);
  const [code, setCode] = useState(`// Auto-generated by Frontend Agent using React Bits
import { useState } from 'react';
import { AnimatedCard } from '@/components/react-bits';
import { Button } from '@/components/ui/button';

export function ProductCard() {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <AnimatedCard
      className="product-card p-6 bg-white rounded-2xl shadow-xl"
      animation="hyperspeed"
      onHover={() => setIsHovered(true)}
      onLeave={() => setIsHovered(false)}
    >
      <div className="w-full h-48 bg-gradient-to-br from-blue-100 to-purple-100 rounded-xl mb-4 flex items-center justify-center">
        <i className="fas fa-image text-4xl text-slate-400"></i>
      </div>
      
      <h3 className="text-xl font-bold text-slate-800 mb-2">
        Premium Wireless Headphones
      </h3>
      <p className="text-slate-600 text-sm mb-4">
        High-quality audio with noise cancellation and 30-hour battery life.
      </p>
      
      <div className="flex items-center justify-between mb-4">
        <span className="text-2xl font-bold text-slate-800">$299.99</span>
        <div className="flex items-center space-x-1">
          <div className="flex text-yellow-400">
            {\`★★★★★\`.split('').map((star, i) => (
              <span key={i} className="text-sm">{star}</span>
            ))}
          </div>
          <span className="text-slate-500 text-sm">(248)</span>
        </div>
      </div>
      
      <Button 
        className={\`w-full py-3 rounded-xl transition-all duration-300 \${
          isHovered ? 'scale-105' : ''
        }\`}
      >
        Add to Cart
      </Button>
    </AnimatedCard>
  );
}`);

  const editorRef = useRef<HTMLTextAreaElement>(null);

  const files = [
    { name: 'src/App.tsx', type: 'tsx', agent: 'Frontend Agent' },
    { name: 'src/components/ProductCard.tsx', type: 'tsx', agent: 'Frontend Agent' },
    { name: 'server/api/products.ts', type: 'ts', agent: 'Backend Agent' },
    { name: 'server/database/schema.sql', type: 'sql', agent: 'Database Agent' },
    { name: 'styles/globals.css', type: 'css', agent: 'UI/UX Agent' }
  ];

  const agents = [
    { name: 'Frontend Agent', status: 'active', color: 'text-cyan-400' },
    { name: 'Backend Agent', status: 'busy', color: 'text-green-400' },
    { name: 'Database Agent', status: 'idle', color: 'text-violet-400' },
    { name: 'UI/UX Agent', status: 'active', color: 'text-pink-400' }
  ];

  const getFileIcon = (type: string) => {
    const icons: Record<string, string> = {
      tsx: 'fab fa-react text-cyan-400',
      ts: 'fab fa-js-square text-blue-400',
      js: 'fab fa-js-square text-yellow-400',
      css: 'fab fa-css3-alt text-blue-500',
      sql: 'fas fa-database text-orange-400',
      json: 'fas fa-code text-green-400'
    };
    return icons[type] || 'fas fa-file-code text-slate-400';
  };

  const getAgentStatus = (status: string) => {
    switch (status) {
      case 'active':
        return 'bg-green-500 animate-pulse';
      case 'busy':
        return 'bg-blue-500 animate-pulse';
      default:
        return 'bg-gray-500';
    }
  };

  useEffect(() => {
    // Simulate real-time code updates
    const interval = setInterval(() => {
      if (!isEditing && Math.random() > 0.7) {
        // Simulate agent making small changes
        const lines = code.split('\n');
        const commentLine = `  // Updated by ${activeAgent} at ${new Date().toLocaleTimeString()}`;
        if (!lines.some(line => line.includes('Updated by'))) {
          lines.splice(2, 0, commentLine);
          setCode(lines.join('\n'));
        }
      }
    }, 5000);

    return () => clearInterval(interval);
  }, [code, isEditing, activeAgent]);

  return (
    <Card className={cn('bg-slate-800/50 border-slate-700', className)}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center space-x-2 text-white">
            <i className="fas fa-file-code text-primary-400"></i>
            <span>Code Editor</span>
          </CardTitle>
          <div className="flex items-center space-x-3">
            <Select value={selectedFile} onValueChange={setSelectedFile}>
              <SelectTrigger className="w-48 bg-slate-700 border-slate-600 text-white">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {files.map((file) => (
                  <SelectItem key={file.name} value={file.name}>
                    <div className="flex items-center space-x-2">
                      <i className={getFileIcon(file.type)}></i>
                      <span>{file.name}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <div className="flex items-center space-x-2 px-3 py-2 bg-slate-700 rounded-lg">
              <div className={cn('w-2 h-2 rounded-full', getAgentStatus('active'))}></div>
              <span className="text-sm text-slate-300">
                {files.find(f => f.name === selectedFile)?.agent || 'AI Agent'}
              </span>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        {/* File Tabs */}
        <div className="flex items-center space-x-1 px-4 py-2 border-b border-slate-700 bg-slate-800/30">
          {files.slice(0, 3).map((file) => (
            <button
              key={file.name}
              onClick={() => setSelectedFile(file.name)}
              className={cn(
                'flex items-center space-x-2 px-3 py-2 rounded-lg text-sm transition-colors',
                selectedFile === file.name
                  ? 'bg-slate-700 text-white'
                  : 'text-slate-400 hover:text-white hover:bg-slate-700/50'
              )}
            >
              <i className={getFileIcon(file.type)}></i>
              <span>{file.name.split('/').pop()}</span>
              {selectedFile === file.name && (
                <button className="text-slate-400 hover:text-white">
                  <i className="fas fa-times text-xs"></i>
                </button>
              )}
            </button>
          ))}
        </div>

        {/* Code Editor */}
        <div className={cn('relative', height)}>
          <textarea
            ref={editorRef}
            value={code}
            onChange={(e) => setCode(e.target.value)}
            onFocus={() => setIsEditing(true)}
            onBlur={() => setIsEditing(false)}
            className="w-full h-full p-4 bg-slate-900 text-white font-mono text-sm resize-none border-0 outline-none"
            style={{ 
              fontFamily: 'Monaco, Menlo, "Ubuntu Mono", monospace',
              lineHeight: '1.5',
              tabSize: 2
            }}
            spellCheck={false}
          />
          
          {/* Line numbers */}
          <div className="absolute left-0 top-4 w-12 h-full bg-slate-800/50 border-r border-slate-700 flex flex-col text-xs text-slate-500 font-mono">
            {code.split('\n').map((_, index) => (
              <div key={index} className="px-2 leading-6 text-right">
                {index + 1}
              </div>
            ))}
          </div>

          {/* AI Assistant Indicator */}
          <div className="absolute top-4 right-4 flex items-center space-x-2 px-3 py-1 bg-slate-800/80 rounded-lg border border-slate-600">
            <div className="w-2 h-2 bg-primary-500 rounded-full animate-pulse"></div>
            <span className="text-xs text-slate-300">AI Assistant Active</span>
          </div>
        </div>

        {/* Status Bar */}
        <div className="flex items-center justify-between px-4 py-2 bg-slate-800/30 border-t border-slate-700 text-xs">
          <div className="flex items-center space-x-4">
            <span className="text-slate-400">
              Lines: {code.split('\n').length}
            </span>
            <span className="text-slate-400">
              Characters: {code.length}
            </span>
            <span className="text-slate-400">
              Language: TypeScript React
            </span>
          </div>
          
          <div className="flex items-center space-x-2">
            <Badge variant="outline" className="text-xs">
              <i className="fas fa-check mr-1 text-green-400"></i>
              No Errors
            </Badge>
            <Button size="sm" variant="ghost" className="text-xs px-2 py-1 h-6">
              <i className="fas fa-save mr-1"></i>
              Save
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
